### ISSUE TITLE
middleware order

### ISSUE THREAD

**Issue by kevinmickey** [evansd/whitenoise#100]
The documentation says to place whitenoise middleware above all others apart from Django's SecurityMiddleware (http://whitenoise.evans.io/en/stable/django.html#enable-whitenoise).  That works for [1.9 when it's at the top](https://docs.djangoproject.com/en/1.9/topics/http/middleware/) but [1.8 puts it at the bottom](https://docs.djangoproject.com/en/1.8/topics/http/middleware/).

I don't know if security can be put at the top for 1.8, or if the docs need more clarification here.

**Comment by evansd** [comment]
It looks like it was a mistake that it was ever placed at the bottom in the 1.8 docs. Here is the commit which moved it to the top and added a hint explaining why:
https://github.com/django/django/commit/8b1f39a727be91aab40bdb37235718ed63ae1d50

**Comment by kevinmickey** [comment]
OK - thanks so much for the link!

**Comment by edmorley** [comment]
I've asked if that docs tweak can be backported to Django 1.8, in:
https://code.djangoproject.com/ticket/24796#comment:11
