### ISSUE TITLE
WHITENOISE_STATIC_PREFIX does not work

### ISSUE THREAD

**Issue by pinguin999** [evansd/whitenoise#101]
Hi devs,

I want to use the WHITENOISE_STATIC_PREFIX in django settings file. 

As I can see there is no point in the code where WHITENOISE_STATIC_PREFIX is read. 

And the GitHub Search only finds WHITENOISE_STATIC_PREFIX in the docs and the change log.

And https://github.com/evansd/whitenoise/commit/a4a4556f5e86fdf4abaf1b48ada55a23ed58dedd looks like not adding this at all.

Thx for any help
Kolja

**Comment by edmorley** [comment]
The config variables are retrieved in:
https://github.com/evansd/whitenoise/blob/v3.2/whitenoise/django.py#L46-L62
...and are constructed from `config_attrs`, so it's expected that the string `WHITENOISE_STATIC_PREFIX` doesn't exist in the source.

Could you paste the settings you're trying to use, as well as WhiteNoise version, whether middleware vs wsgi wrapper etc. Thanks!

**Comment by pinguin999** [comment]
Hi 

I git the whitenoise version from pip today. And I use Django on Windows with Bitnami Django Stack installer. (https://bitnami.com/stack/django)

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',	
]

and this in settings.py

STATIC_ROOT = path.join(PROJECT_ROOT, 'staticfiles').replace('\\', '/')
WHITENOISE_STATIC_PREFIX = '/basislager/static/'
STATIC_URL = '/static/'
WHITENOISE_STATIC_PREFIX = '/basislager/static/'

wsgi file:
import os, sys
sys.path.append('C:/Users/Jangiaghdam/Bitnami Django Stack projects/basislager')
os.environ.setdefault("PYTHON_EGG_CACHE", "C:/Users/Jangiaghdam/Bitnami Django Stack projects/basislager/egg_cache")


from django.core.wsgi import get_wsgi_application
from whitenoise.django import DjangoWhiteNoise 

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "basislager.settings")

application = get_wsgi_application()
application = DjangoWhiteNoise(application)


Part of my HTML

    {% load static from staticfiles  %}
    <script src="{% static 'app/scripts/jquery-2.2.1.min.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script> 


My URL: http://127.0.0.1/basislager/home
And the static url is: http://127.0.0.1/static/app/scripts/jquery-2.2.1.min.js
The file is at http://127.0.0.1/basislager/static/app/scripts/jquery-2.2.1.min.js

Hope that helps

**Comment by evansd** [comment]
Hi @pinguin999, i'm not sure what you're trying to achieve here by using `STATIC_PREFIX` but that looks like correct behaviour to me. The URL being generated is at  http://127.0.0.1/static/ because you have `STATIC_URL` set to `/static/`, and the file is being served at ` http://127.0.0.1/basislager/static/` because you have `WHITENOISE_STATIC_PREFIX` set to `/basislager/static/`. What were you expecting to happen?

As explained in the docs, normally you wouldn't set `WHITENOISE_STATIC_PREFIX` at all and it would be automatically set based on the value of `STATIC_URL` so everything works correctly. It's only if something is rewriting incoming URLs before they reach Django that you might need to use that setting.

**Comment by pinguin999** [comment]
Hi @evansd 
Thank you for your Help. 

I had to set 
WHITENOISE_STATIC_PREFIX = '/static/'

**Comment by evansd** [comment]
Hi @pinguin999, no problem!

If you're just setting `WHITENOISE_STATIC_PREFIX` to the same value as `STATIC_URL` then you don't need to set it at all as WhiteNoise will figure out the correct setting automatically.

I only added that setting to support people with unusual CDN configurations who needed more flexibility -- most users should never need to set it.

Could I make the docs clearer on this? What would help?

**Comment by pinguin999** [comment]
Hi @evansd 

no the docs was very clear. 
I will double check what happens if I remove WHITENOISE_STATIC_PREFIX . I think our setup is not normal.
