### ISSUE TITLE
content-language is the same as the previous request

### ISSUE THREAD

**Issue by oppianmatt** [evansd/whitenoise#103]
If you look at https://github.com/evansd/whitenoise/issues/102

You will see there are Content-Language: headers in the response. They correspond to the previous request (for example I made a request to /cs/search/) and now static content served by whitenoise, i.e. /static/js/search.js will have the content-language set to cs. Same if I go visit /fr/search/, now all the static comes back with fr language.

We have the whitenoise middleware first in the middleware settings, and then later we have the i18n url middleware (actually using 'solid_i18n.middleware.SolidLocaleMiddleware' since it let's us have the main url without a lang prefix).

Should the whitenoise middleware go later? Or should the whitenoise middleware clear the content-language header since static content is language agnostic, and would get a better hit rate that way.

**Comment by evansd** [comment]
This is the kind of issue which the new style of Django middleware (coming in 1.10) was designed to prevent (see point 1 of the [behavioural differences](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware) section). The `SolidLocaleMiddleware` is modifying the response, even though `WhiteNoiseMiddleware` has short-circuited the response cycle.

Within the old middleware framework the only way to fix this is to fix `SolidLocaleMiddleware` to not modify responses to requests that it didn't process e.g. by adding a flag like `request._seen_by_solid_locale = True` in the `process_request` method and then checking for the presence of this flag in the `process_response` method.

Regarding the cache hit rate, the thing that really matters here is the `Vary` header as that specifies the circumstances under which cached results can be reused. In the example you sent, the `Vary` header didn't have `content-language` in it, so the presence of the language header shouldn't affect caching behaviour.

There were some other values (`X-Requested-With` and `X-http2`) in the vary header which I wouldn't have expected, but I guess you have some other middleware which is adding those.
