### ISSUE TITLE
with Django-leaflet, getting static file not found

### ISSUE THREAD

**Issue by ndanielsen** [evansd/whitenoise#105]
Hey David,

Just wanted to first say thank you for maintaining such a helpful package. This is one of my standard go to packages.

I'm using it with leaflet and django-leafet. I keep getting the following error on collectstatic. 

ValueError: The file 'leaflet/draw/leaflet.draw.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fc1be653208>.

it works fine with: STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

Any thoughts or ideas on how to fix this?

Thank you so much again for maintaiinng this.

**Comment by korymath** [comment]
+1

**Comment by evansd** [comment]
@ndanielsen Glad you've found it useful!

It looks like this is a bug in django-leaflet: https://github.com/makinacorpus/django-leaflet/pull/149

You can still use WhiteNoise with the the default `django.contrib.staticfiles.storage.StaticFilesStorage` storage backend, you just won't get optimal caching behaviour and compression.
