### ISSUE TITLE
Django 1.10 with GzipManifestStaticFilesStorage breaks on absolute path in CSS with double slash

### ISSUE THREAD

**Issue by reverie** [evansd/whitenoise#106]
After upgrading Django to 1.10, my `manage.py collectstatic` command broke with an error like this one: 

`django.core.exceptions.SuspiciousFileOperation: The joined path (/fonts/crimson/CrimsonText-Bold.ttf) is located outside of the base path component (/Users/andrew/tmp/verse_collectstatic_test/_staticfiles)`

This occurs with whitenoise 2.0.6 or 3.2.1. Downgrading to Django 1.9 fixes the issue (`collectstatic` runs successfully), as does removing the line `STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'` from my settings.py. The static file it is attempting to process in the above example is a .css file containing:

```
@font-face {
  font-family: "Crimson";
  src: url("/static//fonts/crimson/CrimsonText-Bold.ttf");
  font-weight: bold;
}
```

Note the double slash in the font path. This is a typo, but it is not a syntactic or semantic error, and it worked fine before. It runs fine if I fix the double-slash. This is an easy workaround, but I am filing this issue because it may be tricky for other users to diagnose, and because there may be some more dangerous underlying bug.

**Comment by evansd** [comment]
Thanks for the detailed report. I'm 99% confident this is an issue with Django rather than WhiteNoise though, as WhiteNoise doesn't do any of its own URL processing.

If you change the line in `settings.py` to:
```python
STATICFILES_STORAGE =  'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```
do you still get the same error?

If so then the bug should be reported against Django.

**Comment by reverie** [comment]
You're right! Good call.

**Comment by edmorley** [comment]
For anyone wanting to follow along, the upstream ticket is:
https://code.djangoproject.com/ticket/27201
