### ISSUE TITLE
Handle `OSError: [Errno 36] File name too long:` instead of throwing 500 error.

### ISSUE THREAD

**Issue by mrmachine** [evansd/whitenoise#110]
I think this only shows up when `WHITENOISE_AUTOREFRESH=True`, but still I think this should return a 404 if the file is not found, no matter what type of path is passed in to whitenoise (too long, badly encoded, whatever).

**Comment by evansd** [comment]
@mrmachine Thanks for raising this. I agree that this should result in a 404 not a 500.
