### ISSUE TITLE
Include deployment suggestion in documentation

### ISSUE THREAD

**Issue by bittner** [evansd/whitenoise#114]
It would be helpful if the [WhiteNoise documentation](https://whitenoise.readthedocs.io/en/latest/) demonstrated how to actually deploy a Django application.

From [reading the docs](https://whitenoise.readthedocs.io/en/latest/django.html) I would guess you're suggesting to actually run `python manage.py runserver` directly. In other words, say with Docker, you would come up with 2 containers, one for Django and one for Postgres, in a simple case. Is that really it? :worried: 

If not, how would a setup look like that used uWGI or gunicorn (without Nginx or Apache, obviously)? The [Django docs](https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/) unfortunately talk about combining, e.g., `uwsgi` with Apache or Nginx just as if that were the only good solution.

**Comment by evansd** [comment]
Thanks for the suggestion, but I think that's beyond the scope of WhiteNoise. In fact, the whole point of WhiteNoise is to provide simple static file handing regardless of how you choose to deploy your application, so it deliberately doesn't specify one particular method of deployment.

I'm not sure if using `runserver` in production is a good idea or not (it might be fine, but as far as I know it's intended more as a development server than a production one). I've tended to use gunicorn myself.

You're right that the Django docs on deployment haven't been updated to reflect the new tools we now have. But if you Google for "django docker" you should fine plenty of advice on deploying Django apps with Docker.

The benefit of WhiteNoise is that once you've got the wsgi app deployed and running you don't need to do anything _extra_ to get static files working.

**Comment by bittner** [comment]
Thanks, Dave, for the instant reply. Happy New Year, by the way! :champagne:

No, really, _"once you've got the wsgi app deployed"_ is a hard task for many developers. Unfortunately, it's not done with _"do a web search for ´django docker´"_.

What I suggest is _not_ doing something that is out of scope of this app and its documentation. It's avoiding and doing away with misunderstandings, and instead pointing into the right direction. Also, because WhiteNoise changes the way we think about deployment best practices (i.e. web proxy for static files) it's more than just _"provide simple static file handing"_ as far as the docs are concerned.

I've tried to point out that the current documentation may mislead developers into thinking `runserver` is - _finally!_ **\*sic\*** - a valid option for production. Actually it's not.

Pure uWSGI, Pure Gunicorn
----------------------
Can you draft your pure Gunicorn deployment in this ticket and we try to figure out how to best promote a "correct way with WhiteNoise"? In my opinion there are two options:

- Extend the Django documentation for [deployment with Gunicorn](https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/gunicorn/) and [deployment with uWSGI](https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/gunicorn/), and point to those updated docs, or
- Add sample deployment configurations for Gunicorn and uWSGI in the [WhiteNoise docs](https://whitenoise.readthedocs.io/en/latest/), and maybe point to those chapters from Django's deployment documentation chapters.

Option 2 may also translate to:
- Move all common deployment information from the chapters "[Using WhiteNoise with Django](https://whitenoise.readthedocs.io/en/latest/django.html)", "[Using WhiteNoise with Flask](https://whitenoise.readthedocs.io/en/latest/flask.html)", "[Using WhiteNoise with any WSGI application](https://whitenoise.readthedocs.io/en/latest/base.html)" into a single chapter dedicated to "New-style Deployment" without web proxy.

**Comment by evansd** [comment]
Hi Peter,

Happy New Year to you as well!

Yes, you're right that deploying a wsgi app is still a non-trivial task and I was a bit glib in my response. That "search for 'django docker'" remark was really just my polite way of saying "I'm not going to hold your hand while you learn Docker" ;) The whole area is still a minefield, and there's lots of conflicting advice out there, so I'm not pretending it's easy.

I still don't see how general advice on deploying Django is within scope for the WhiteNoise docs, but if you know of any good guides (or want to write one yourself) then I'd happily link to it. I think what really needs to happen is an overhaul of the official Django docs to bring them up to do date, but no one seems to have stepped up to do that so far.

If there are specific parts of the docs which are misleading, or where I seem to suggest using `runserver` in production, then please point them out and I'll happily fix them.

**Comment by bittner** [comment]
I will look over the docs again and try to figure out what to change to avoid misunderstandings. (I won't promise a deadline for this, though---sorry, but I seriously plan to get back to it.)

Some more thoughts, questions and cross-references in the meantime:

- When deploying a Django project without a web proxy, who handles the **SSL certificate** stuff (for https), which is typically handled by Nginx or Apache?
- **Eldarion** seems to use WhiteNoise [in their proposed deployment setup](https://eldarion-gondor.github.io/docs/how-to/setup-deploy-first-django-project/), which may serve as a reference point or role model. (Found in the [Server Best Practices](http://docs.python-guide.org/en/latest/scenarios/web/#server-best-practices) section of Kenneth Reitz' Python Guide.)

**Comment by subodh-malgonde** [comment]
@bittner Did you figure this part out? I am also stuck on deploying a Django + whitenoise application using gunicorn. How did you handle the SSL certificate stuff?

**Comment by bittner** [comment]
No, sorry. But thanks for reminding me. I've not done anything substantial in this direction yet. I didn't have the necessity.

I saw you've [posted the same question](https://www.reddit.com/r/django/comments/bjdokh/how_to_deploy_a_django_whitenoise_application/) on Reddit, too. For what I see in the answers people seem confused.

I'd love follow @evansd's suggestion from above and update the Django docs:

> I think what really needs to happen is an overhaul of the official Django docs to bring them up to do date, but no one seems to have stepped up to do that so far.

... but I'd have to find time (or a customer requesting) to dig into the topic and come up with solid recommendations. You may find some progress in the next months in the [painless-continuous-delivery](https://github.com/painless-software/painless-continuous-delivery/) project or the [APPUiO Django examples](https://gitlab.com/appuio) I'm working on.

Regarding TLS/SSL, nowadays the parameters have changed slightly: It's all about Kubernetes now, and that handles the setup for you in the routes.

**Comment by subodh-malgonde** [comment]
@bittner I did figure things out. I have posted details here https://github.com/evansd/whitenoise/issues/219. Let me know what you think.
