### ISSUE TITLE
Using WhiteNoise with S3

### ISSUE THREAD

**Issue by amberdiehl** [evansd/whitenoise#116]
Hi There,

I am attempting to use WhiteNoise with my Amazon S3 bucket after previously (and successfully) setting the bucket up and moving assets there without WhiteNoise. I am also using WhiteNoise in my local environment which accesses the same static files locally.

I 'think' WhiteNoise is working okay locally--when I run collectstatic I have a bunch of files now in my project/staticfiles folder including what appears to be compressed versions.

However, when I run collectstatic on the production server (or in my local environment with the settings to act like production) I get a very different result where it keeps copying static files only for admin and one of my apps. None of the assets sitting in the root static folder are being touched and nothing appears to be minimized. 

Here are the bits I think you need to inspect in my settings file(s):

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    ...

DEBUG = True

if DEBUG:

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.10/howto/static-files/

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_DIRS = (os.path.join(BASE_DIR, '..', "static"),)
    STATIC_URL = '/static/'

    MEDIA_ROOT = os.path.join(MAIN_DIR, 'media')
    MEDIA_URL = '/media/'

else:

    # ** PRODUCTION STATIC AND MEDIA SETTINGS **
    # Use while running locally only for debugging/testing purposes
    AWS_STORAGE_BUCKET_NAME = '***'
    AWS_ACCESS_KEY_ID = '***'
    AWS_SECRET_ACCESS_KEY = '***'

    AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

    #STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
    #STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

    STATIC_HOST = 'https://***.cloudfront.net'
    STATICFILES_LOCATION = 'static'
    STATIC_URL = "https://%s/%s/" % (STATIC_HOST, STATICFILES_LOCATION)
    STATICFILES_STORAGE = 'custom_storages.StaticStorage'

    MEDIAFILES_LOCATION = 'media'
    MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
    DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

CONTENT_TYPES = ['image', 'video']
MAX_UPLOAD_SIZE = "5242880"

And here is the project tree for help:

dandeliondiary_project/
   app1/
      static

   app2/
      ...

   dandeliondiary/
      settings/
         base.py
         production.py
      staticfiles/

      manage.py
      static/
          css/
          images/
          plugins/

App1 static is being found and copied (but I don't see any files being compressed). Nothing is being done with static/.

Any help would be greatly appreciated.

Cheers,
Amber

**Comment by evansd** [comment]
Hi Amber,

I think there's been a bit of confusion here as the point of WhiteNoise is so you don't need to use S3 to serve your static files (media files are different and S3 is still a good choice for them). So you should have
```python
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```
in both development and production.

The only difference between development and production settings should be in your `STATIC_URL` setting so that you can use a CDN like Cloudfront in production. Did you see the instructions for setting up Cloudfront here?
http://whitenoise.readthedocs.io/en/stable/django.html#use-a-content-delivery-network

**Comment by amberdiehl** [comment]
Hi Dave,

Thank you, very much, for your speedy response.

I understand that WhiteNoise is supposed to prolong or eliminate the need for using a CDN. However, since I need one any way for user (media) files, I thought it might make the most sense to have both static assets and media hosted via a CDN.

I did read and use your documentation; hence as you may see why I implemented the STATIC_HOST bit and that is used for the STATIC_URL.

Unfortunately, when I change the STATIC_STORAGE to the above statement, as used when serving files locally, I get the following error:

ImproperlyConfigured at /public/
You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.

I experimented a little bit seeing if I could 'fake it' with STATIC_ROOT set but nothing worked. 

The settings you see there for production are what work without using WhiteNoise on S3. In looking at your documentation, it appeared the only thing I needed to do was create the distribution on Amazon and then simply change the URL so that it pointed to that...

Thanks again for your help.

Kind regards,
Amber

**Comment by evansd** [comment]
Hi Amber,

WhiteNoise is definitely intended to be used with a CDN, but Amazon S3 isn't a CDN -- it's a file storage service. Amazon's CDN service is called Cloudfront. Often Cloudfront and S3 are used together, but they don't have to be and this may be part of the confusion.

From those settings you've pasted I can see a couple of issues:
1. You define `STATICFILES_DIRS` in your DEBUG stanza, but don't define it for production
2. In production, your `STATIC_URL` setting starts with `https` but it has the value of `STATIC_HOST` interpolated into it which also starts `https` so the result won't be a valid URL.

I'll repeat my recommendation that the only thing that should differ between production and development (as far as static files go) is the value of `STATIC_URL`, as per the docs:
```python
STATIC_HOST = 'https://************.cloudfront.net' if not DEBUG else ''
STATIC_URL = STATIC_HOST + '/static/'
```
If you do that, and set up Cloudfront correctly, then everything should work and you'll be using a CDN in production. But of course you're free to set it how you want!

Best wishes,

Dave

**Comment by amberdiehl** [comment]
Hi Dave,

Thank you for your kind replies and willingness to help me. I think this 'issue' is because I'm a beginner with Django/Python and misunderstood how serving static files work. After (a lot more) reading, researching new error(s) I created, etc. I believe my core issue is that I am attempting to use storages/boto and WhiteNoise together.

Kind regards,
Amber

**Comment by evansd** [comment]
Hi Amber,

You're welcome! It's not easy starting out with this stuff and I'm just sorry I don't have more time to help. It sounds like you're figuring things out though.

All the best,

Dave
