### ISSUE TITLE
Files not compressed when called by JavaScript

### ISSUE THREAD

**Issue by mimischi** [evansd/whitenoise#119]
We're using [Swipebox](http://brutaldesign.github.io/swipebox/) in a project, to show a small image gallery. WhiteNoise is running perfectly for the rest of the site.

Basically the Swipebox overlay is opened after you click on a button. The problem now is, that Swipebox is supposed to show arrow icons to switch between images. These buttons are only put into the DOM after you click that specific button, for the overlay to come up. They are not loaded beforehand.

The buttons are then embedded like so:

```
<div id="swipebox-arrows">
<a id="swipebox-prev" style="background-image: url("background-image: url("https://myurl/static/preview/src_swipebox/img/icons.486f0204fc9b.svg");");" class="disabled"></a>
<a id="swipebox-next" style="background-image: url("background-image: url("https://myurl/static/preview/src_swipebox/img/icons.486f0204fc9b.svg");");"></a>
</div>
```

The URL gets changed, but the actual file never gets compressed/cached and therefore results in a 404 error inside the browsers console. Not sure how to solve that or what to do to get rid of this error.

**Comment by evansd** [comment]
Hi, this doesn't sound like a WhiteNoise issue to me but more likely an interaction between Django's caching storage and the setup of Swipebox. Can you try changing the storage setting to:
```python
STATICFILES_STORAGE =  'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```
If you still get the same issue then it's not a problem with WhiteNoise itself.

If you can post a link to a minimal Django project which reproduces the issue then I could take a look.

**Comment by mimischi** [comment]
You were right. This was totally not a problem with WhiteNoise, neither with Django. Swipebox is messing up the cached files.
