### ISSUE TITLE
GzipManifestPipelineStorage could not find file

### ISSUE THREAD

**Issue by pythdasch** [evansd/whitenoise#121]
Hi,

thanks for this nice library ! 

All is doing fine when I collectstatic, it normally creates the cache files, all seems fine.
```

`Post-processed 'compiled/dashboard.min.css' as 'compiled/dashboard.min.7058dfd4311a.css'
Post-processed 'compiled/common.min.js' as 'compiled/common.min.ccc4b6941036.js'
Post-processed 'compiled/form.min.js' as 'compiled/form.min.f919b770e800.js'
Post-processed 'compiled/dashboard.min.js' as 'compiled/dashboard.min.a9893fbed25e.js'
```
`
but when I get on the website : 

I have a 500 error because of : 
`ValueError at / The file ‘compiled/compiled.min.css’ could not be found with <core.custom_storage.GzipManifestPipelineStorage object at 0x7f1bd2aa87d0>.
`
That's strange that he doesn't look for the cached version of compiled/compiled.min.css
...

I did the installation of all this with this tutorial
https://devcenter.heroku.com/articles/django-assets

I also added cloudfront and pipeline

Here is my custom storage : 
```
`from pipeline.storage import PipelineMixin
from whitenoise.django import GzipManifestStaticFilesStorage


class GzipManifestPipelineStorage(PipelineMixin, GzipManifestStaticFilesStorage):
pass`

```
and whitenoise settings
```
`STATIC_HOST = 'https://********.cloudfront.net'
WHITENOISE_STATIC_PREFIX = "/static/" # Important to make Whitenoise and cloudfront work together
STATIC_URL = STATIC_HOST + '/static/'`
```

In the logs the error is launch there : 
```
`File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
2017-02-14T12:03:30.772543473Z app[web.1]:     cache_name = self.clean_name(self.hashed_name(name))
2017-02-14T12:03:30.772545462Z app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
2017-02-14T12:03:30.772547519Z app[web.1]:     (clean_name, self))
```
`
if someone can help me would it be awesome !

**Comment by evansd** [comment]
Hi, I think this is a problem with django-pipeline. You don't have to use a special storage backend with WhiteNoise (it's just there to add compression support) so I'd try getting it working with the normal `PipelineStorage` first.

I'm closing this is as it doesn't seem to be a bug in WhiteNoise, but you could ask on StackOverflow and see if anyone can help.
