### ISSUE TITLE
Exception when running tests with Django 1.11

### ISSUE THREAD

**Issue by jameschristopher** [evansd/whitenoise#130]
There seems to be an issue with how Whitenoise interacts with the `manifest_strict` attribute on `django.contrib.staticfiles.storage.ManifestFilesMixin` when running tests.

```
ValueError: Missing staticfiles manifest entry for
```
[It seems the new `manifest_strict` attribute is automatically set to True, whereas the old behavior was as if it was set to False.](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#manifeststaticfilesstorage) This error does not appear when `STATICFILES_STORAGE` is the default. [Here is where the `manifest_strict` attribute is used by django.](https://github.com/django/django/blob/master/django/contrib/staticfiles/storage.py#L421)

Thoughts? Maybe someone can attempt to replicate the issue?

**Comment by evansd** [comment]
Hi @jameschristopher,

Try setting
```
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```
If the issue persists with this setting then the problem isn't with WhiteNoise. If the issue occurs when using the WhiteNoise storage backend but not when using `ManifetsStaticFilesStorage` then let me know and I'll investigate further.

**Comment by jameschristopher** [comment]
Thank you. And the error still occurred by setting 
```STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'```
Upon further reading of the docs they actually say to not use `'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'` during testing. Since the WhiteNoise backend subclasses `ManifestStaticFilesStorage` I'll just remove the WhiteNoise backend when testing. I'll close this issue.

**Comment by KrzysztofMadejski** [comment]
I had the same error. My problem is that I was running collectstatic with other settings file than I should. Stupid mistake.

**Comment by kovaacs** [comment]
```class TestX(StaticLiveServerTestCase):
    def test_x(self):
        with self.settings(STATICFILES_STORAGE=''):
            self.assert...
```

You avoid having to `collectstatic` or mess with your `settings.py`.
