### ISSUE TITLE
testing installation

### ISSUE THREAD

**Issue by andreav** [evansd/whitenoise#131]
Hello,
I have installed last pip version, 3.3.0 with Django 1.9.

```
MIDDLEWARE_CLASSES = (
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
...
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

I continue getting status code 200  and not 304 when retrieving static files.

This happens in all these scenarios:
* development running applciation with runserver --nostatic
* development running applciation with gunicorn
* producition (DEBUG=False)

Files are correvtly generated, ie.:
* t2g-polyfills.js
* t2g-polyfills.js.gz
* t2g-polyfills.615dcc41d2ff.js
* t2g-polyfills.615dcc41d2ff.js.gz

I do not know how to thoubleshoot this problem.
I also created a minimal project, only Djano and whitenoise but still same behaviour.

As a request/response example (directly from production) [form Chrome Network analizer]:

```
General:

Request URL:http://trip2go.tours/static/site/js/t2g-polyfills.615dcc41d2ff.js
Request Method:GET
Status Code:200 OK
Remote Address:139.59.149.27:80
Referrer Policy:no-referrer-when-downgrade

Response Headers:

Access-Control-Allow-Origin:*
Cache-Control:max-age=315360000, public, immutable
Connection:keep-alive
Content-Encoding:gzip
Content-Language:en
Content-Length:362
Content-Type:application/javascript; charset="utf-8"
Date:Thu, 13 Apr 2017 09:10:48 GMT
Last-Modified:Thu, 13 Apr 2017 08:53:46 GMT
Server:nginx/1.10.0 (Ubuntu)
Vary:Accept-Encoding, Accept-Language
X-Frame-Options:SAMEORIGIN

Request Headers:

Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,it-IT;q=0.6,it;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Cookie:csrftoken=8wjypAYfBB6Nb3cGKchv2NqufKDcXxsU
Host:trip2go.tours
Pragma:no-cache
Referer:http://trip2go.tours/trips/search/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
```

Thank you.

**Comment by edmorley** [comment]
The request headers contain `Cache-Control:no-cache` and also don't specify `If-Modified-Since`. This would imply the cache is disabled, which it is by default when using the developer tools. Make sure to uncheck the `disable cache` check-box on the Chrome devtools "Network" tab. Chrome and Firefox also skip the HTTP 304 in many cases (in Chrome's case due to recently added logic, for Firefox due to WhiteNoise using the `immutable` directive) and show a fake HTTP 200 from memory cache (but says zero bytes transferred).

Also when refreshing the page do a standard refresh and not a "shift+refresh".

To demonstrate this is working:
```
$ curl -sSfI http://trip2go.tours/static/site/js/t2g-polyfills.615dcc41d2ff.js | grep 'Last-Modified'
Last-Modified: Thu, 13 Apr 2017 08:53:46 GMT

$ curl -I http://trip2go.tours/static/site/js/t2g-polyfills.615dcc41d2ff.js -H 'If-Modified-Since: Thu, 13 Apr 2017 08:53:46 GMT'
HTTP/1.1 304 Not Modified
Server: nginx/1.10.0 (Ubuntu)
Date: Thu, 13 Apr 2017 09:48:04 GMT
Content-Length: 0
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding, Accept-Language
Content-Language: en
Cache-Control: max-age=315360000, public, immutable
```

**Comment by evansd** [comment]
The example request you gave does not contain an `If-Modified-Since` header (probably it was generated by pressing F5 in Chrome which explicitly ignores cached responses). If you make the same request with the correct cache headers a 304 is returned as expected:
```
curl -H 'If-Modified-Since: Thu, 13 Apr 2018 13:10:33 GMT' -I http://trip2go.tours/static/site/js/t2g-polyfills.615dcc41d2ff.js

HTTP/1.1 304 Not Modified
Server: nginx/1.10.0 (Ubuntu)
Date: Thu, 13 Apr 2017 09:57:51 GMT
Content-Length: 0
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Vary: Accept-Encoding, Accept-Language
Content-Language: en
Cache-Control: max-age=315360000, public, immutable
```

**Comment by evansd** [comment]
@edmorley Ha! You just beat me to it. Thanks!

**Comment by andreav** [comment]
Thank you very much boys!
