### ISSUE TITLE
Static files being served without unique hash

### ISSUE THREAD

**Issue by Edke** [evansd/whitenoise#133]
Hello.

Testing whitenoise, followed instructions but static files rendered using static tag are missing unique hash. Using in my Django app, tested in development mode and production using uwsgi. 

- middleware is configured
- using static tag
- using whitenoise storage
- collectstatic executed before uwsgi
- staticfiles.json  is in place within static files folder

Still statics are rendered without unique part:

```html
<script type="text/javascript" src="/static/design2016/libraries/jquery-1.12.3.min.js"></script>
```
Although URL with unique name is served properly: `/static/design2016/libraries/jquery-1.12.3.min.c07f2267a050.js`

**Comment by ervoiox** [comment]
Is `DEBUG` is set to `False`?

**Comment by Edke** [comment]
@ervoiox true, setting DEBUG to False worked ! Thank you. 

So in DEBUG = True and development mode unique names are not generated, right ?

**Comment by edmorley** [comment]
Correct, since files are instead served with `Cache-Control: max-age=0`

**Comment by Edke** [comment]
OK, understood, really likes this, we are moving heavily towards webpack integrations with Django but for small projects it's total overkill. Using WhiteNoise for small / regular projects and Webpack for projects with intense frontend dev (Angular 2.x/React) is something that should work nicely together. 

Thank you, looking for project to test this, biggest issue will be to run in our CI container during docker build to include statics within container layer.
