### ISSUE TITLE
Different timestamps for uncompressed and compressed files

### ISSUE THREAD

**Issue by jaap3** [evansd/whitenoise#134]
The [`ngx_http_gzip_static_module`](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) docs say:

>  It is recommended that the modification date and time of original and compressed files be the same.

Currently this is (usually) the case for the "hashed" version of the assets, but not for the originals. Is it be possible to ensure that the created/modified times of the compressed assets matches the timestamps of the source file?

**Comment by evansd** [comment]
@jaap3 Can I just check the use case here? Is this because you're using the WhiteNoise storage backend to create compressed files but then serving them through nginx, rather than through WhiteNoise?

**Comment by jaap3** [comment]
Yes, that's exactly what we're doing.

**Comment by edmorley** [comment]
I've previously wondered whether splitting out the compression parts to another package might be worthwhile? (Or using another tool if one exists.)

The compression parts feel like something that would be useful for all stacks, not just python+whitenoise, and there are lots of additional improvements that might be scope creep here, but useful in a generic tool (eg multi-threaded compression).

**Comment by edmorley** [comment]
Plus if WhiteNoise ever was merged into Django, I imagine the compression parts might not be accepted into core, so need to be standalone anyway.

**Comment by jaap3** [comment]
Thank you!
