### ISSUE TITLE
Can't figure out correct setup with Heroku in production mode

### ISSUE THREAD

**Issue by nadzimo** [evansd/whitenoise#137]
Hello,

I've followed the instructions to set up whitenoise in the docs. On my localhost when I'm using Django's development server with `DEBUG=True` in `settings.py` my app works fine, but I'm having trouble serving staticfiles on Heroku when `DEBUG=False`. When I try to load any url (eg. mysite.com/) I get a 400 Bad Request response, except if I try to load Django's admin app it works fine (mysite.com/admin/) and I see versioned static files being served (with the hash of the file in the name).

`settings.py`:
```
ALLOWED_HOSTS = ['*']
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') #I also tried PROJECT_ROOT instead of BASE_DIR
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, 'static'),
]
```

I also wanted to see if I could try serving the static files with Django's built in staticfiles app like the [Whitenoise troubleshooting doc suggested](http://whitenoise.evans.io/en/stable/django.html#storage-troubleshoot), but it seems I would need to have access to Heroku's server configuration [as per Django's doc](https://docs.djangoproject.com/en/1.10/howto/static-files/deployment/) which is not possible with Heroku.
I also tried following [Heroku's instructions here](https://devcenter.heroku.com/articles/django-assets) but to no avail.

I can see collectstatic is running correctly without failing when I deploy on Heroku, and as proof as mentioned I can see the static assets of the django /admin/ app being served correctly.

Could you please offer some guidance?

**Comment by edmorley** [comment]
What do the Heroku logs say? (Presuming Django logging working correctly)
https://devcenter.heroku.com/articles/logging

**Comment by nadzimo** [comment]
Thanks for the quick reply.
When I load my app's home url I only get the below log records. 

```
2017-07-10T23:49:53.803892+00:00 heroku[router]: at=info method=GET path="/" host=mysite.herokuapp.com request_id=b8dfec86-2999-41a5-b113-8ba3042e82d7 fwd="90.74.154.51" dyno=web.1 connect=1ms service=48ms status=400 bytes=395 protocol=https
2017-07-10T23:49:54.393149+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=mysite.herokuapp.com request_id=aa2f1b75-4fc0-4228-bdfe-058c1bff952b fwd="90.74.154.51" dyno=web.1 connect=6ms service=47ms status=400 bytes=395 protocol=https
```

**Comment by nadzimo** [comment]
So I finally found the error. 
In the template that the homepage was loading I was loading a script source with this
`{% static '/path/to/script/somescript.js' %}`
the leading forward slash was causing the issue. So instead it should be
`{% static 'path/to/script/somescript.js' %}`

It's not clear to me though how setting `DEBUG=False` causes this issue when it was working perfectly fine with the forward slash with `DEBUG=True`.

**Comment by thecookiestech** [comment]
@nadzimo thanks!!!! 👍
