### ISSUE TITLE
4.0 Brotli compression is never used

### ISSUE THREAD

**Issue by fuwaneko** [evansd/whitenoise#138]
Due to regular expression mismatch, instead of "brotli" it should match to "br" in header.

Expression compiles [here](https://github.com/evansd/whitenoise/blob/master/whitenoise/responders.py#L162), matches [here](https://github.com/evansd/whitenoise/blob/master/whitenoise/responders.py#L180). But StaticFile is constructed with "brotli" as encoding, instead of "br" — [here](https://github.com/evansd/whitenoise/blob/master/whitenoise/base.py#L191).

I also wonder why there's no best compression selection mechanism, it seems code just uses the first match.

**Comment by evansd** [comment]
Oh, good catch! Thank you. I've added some more tests around the Brotli handling and fixed this bug.

The encoded files are pre-sorted by size, so the first match is always the best match. I've added some comments to make this clearer.

Closed in 8c16bbccfcd771d0f434d11a6609c95a93323102
