### ISSUE TITLE
Whitenoise problems with DEBUG=False

### ISSUE THREAD

**Issue by racitup** [evansd/whitenoise#144]
I'm a bit stumped having tried to get whitenoise working for a few days now. I'm testing locally with gunicorn before I deploy to Heroku. I've followed all the guides I could find about Django and whitenoise but with no luck and hope someone can help.

The pruned **config** (let me know if there's anything else might be involved):
```
MIDDLEWARE_CLASSES = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    ...
STATIC_URL = '/static/'
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1', '127.0.0.1:8000']
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static_public', 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

The **process**:
```
./manage.py collectstatic
gunicorn myapp.wsgi
<browser to http://127.0.0.1:8000>
```

What **happens**:

- Collectstatic gathers all the files okay and they are visible in the right directory:
`2855 static files copied to '/Users/rich/Documents/source/heroku-test/static_public/static', 2855 post-processed.`
- A partially rendered page and browser console 404 errors for GETs matching those below
- The static folder also has a CACHE directory which contains all of the "Not found" files below which appear to be created as they are accessed
- If I browse to one of the "Not found" files directly, sometimes they appear, sometimes not. It seems to be related to waiting a minute or two before trying to access the file.

The gunicorn **console**:
> [2017-08-26 23:16:59 +0100] [20019] [INFO] Starting gunicorn 19.6.0
> [2017-08-26 23:16:59 +0100] [20019] [INFO] Listening at: http://127.0.0.1:8000 (20019)
> [2017-08-26 23:16:59 +0100] [20019] [INFO] Using worker: sync
> [2017-08-26 23:16:59 +0100] [20036] [INFO] Booting worker with pid: 20036
> [2017-08-26 23:17:27,518 django.request] WARNING: Not Found: /
> [2017-08-26 23:17:27,815 django.request] WARNING: Not Found: /static/CACHE/js/15656dcc525b.js
> [2017-08-26 23:18:12,285 django.request] WARNING: Not Found: /
> [2017-08-26 23:18:12,498 django.request] WARNING: Not Found: /static/CACHE/js/24e0a4ecdb71.js

Could this be some weird interaction with the Django cache? I've left the Django cache backend setting at the default.

**Comment by evansd** [comment]
Are you using some other library which integrates with static files like django-compressor? That CACHE directory sounds like something django-compressor might create. Can you post your full settings file?

**Comment by racitup** [comment]
I think you've hit the nail on the head; yes django-compressor is in use. I'm not familiar with it so will have a dig and see if I can fix it myself first. Is there any advantage to using both do you think, or should I just remove compressor?

**Comment by racitup** [comment]
Thanks for the response. I can confirm it is a django-compressor problem. I'm trying dj-static instead just because it seems the path of least resistance. I've documented the problem [here](https://github.com/awesto/django-shop/issues/645).
