### ISSUE TITLE
Try to work around leftover intermediate ManifestStaticFilesStorage files

### ISSUE THREAD

**Issue by edmorley** [evansd/whitenoise#147]
The stock Django `ManifestStaticFilesStorage` storage back-end has to loop through the files several times when creating the hashed versions to try and handle nested/circular dependencies. Currently this results in intermediate files being left behind, for example looking at `contrib.admin`'s output:
```
css/base.31652d31b392.css
css/base.5af66c1b1797.css
css/base.6b517d0d5813.css
css/base.css
...
```

This is currently unavoidable on Django's side until at least Django 3.0 ([see here](https://groups.google.com/forum/#!topic/django-developers/fmfQvuHBStk)).

When using WhiteNoise's `CompressedManifestStaticFilesStorage` (from current master, 9d3ad51f7f05e5391ec6f2f03211d958a08e374f) , the resultant `base.css` related files are:
```
css/base.31652d31b392.css
css/base.31652d31b392.css.br
css/base.31652d31b392.css.gz
css/base.5af66c1b1797.css
css/base.6b517d0d5813.css
css/base.6b517d0d5813.css.br
css/base.6b517d0d5813.css.gz
css/base.css
css/base.css.br
css/base.css.gz
```

And even with `WHITENOISE_KEEP_ONLY_HASHED_FILES` set to `True`, there are still many redundant files:
```
css/base.31652d31b392.css
css/base.31652d31b392.css.br
css/base.31652d31b392.css.gz
css/base.5af66c1b1797.css
css/base.6b517d0d5813.css
css/base.6b517d0d5813.css.br
css/base.6b517d0d5813.css.gz
```

Compare this to the file list in `staticfiles.json`, which only has one `base.css` related entry:
```
{
    "admin/css/base.css": "admin/css/base.6b517d0d5813.css",
    ...
}
```

It would be great if `CompressedManifestStaticFilesStorage` could try and remove these intermediate files and in the example above only keep `base.6b517d0d5813.css{,.bz,.gz}`.

Also, I can't figure out why only some of the intermediate files get the compressed versions rather than all or none? For example `base.5af66c1b1797.css` doesn't get compressed versions. Bit strange.

**Comment by edmorley** [comment]
> Also, I can't figure out why only some of the intermediate files get the compressed versions rather than all or none? For example base.5af66c1b1797.css doesn't get compressed versions. Bit strange.

Ah so not all of the intermediate files are yielded - the first intermediate file is, here:
https://github.com/django/django/blob/86a18dc46aae3a4a6410e3f3d864fa0ec4e5b2cd/django/contrib/staticfiles/storage.py#L239-L240

...but later ones are not:
https://github.com/django/django/blob/86a18dc46aae3a4a6410e3f3d864fa0ec4e5b2cd/django/contrib/staticfiles/storage.py#L303-L304

This is really the worst of both worlds -- ideally either the `HashedFilesMixin`'s `post_process()` should yield **all** files that were created (including every intermediate), or only the final files. At the moment it does something halfway between the two.

This issue was in fact mentioned in the PR that added this, but unfortunately not resolved:
https://github.com/django/django/pull/6507#r61024158

**Comment by evansd** [comment]
The same workaround mentioned in #150 also fixes this issue.

**Comment by edmorley** [comment]
My bad for not updating these issues with the experiments/WIPs I have locally!

The approach I tried was to defer the compression phase until after the main yield loop and use `self.manifest` for the final list of files. Is this similar to your workaround?

The dilemma I had with that approach was that (a) it means compression starts later, which with multi-threading can actually slow the end-to-end time depending on the proportion of CSS to non-CSS files, (b) once Django fixes it, the compression parts will want to be moved back into the `yield` loop.

Anyway I should really finish up the branch I have for multi-threading (#148) soon :-)

**Comment by edmorley** [comment]
Ah that's quite a bit more of a complex approach? I'd hoped we might be able to discuss in a PR? :-)

**Comment by evansd** [comment]
Happy to do that. PR here:
