### ISSUE TITLE
CompressedStaticFilesMixin compresses each CSS file multiple times

### ISSUE THREAD

**Issue by edmorley** [evansd/whitenoise#150]
I noticed as part of #148 (by modifying `CompressedStaticFilesMixin` so that it passes `quiet=False` to `Compressor` to give more log output) that CSS files are run through the compressor multiple times:
```
$ ./manage.py collectstatic --noinput -v 3 > collectstatic.log
$ grep -e 'Brotli compressed .*\.css ' collectstatic.log | sort
Brotli compressed /home/vagrant/test/test/static/admin/css/base.31652d31b392.css (15K -> 3K)
Brotli compressed /home/vagrant/test/test/static/admin/css/base.6b517d0d5813.css (15K -> 3K)
Brotli compressed /home/vagrant/test/test/static/admin/css/base.6b517d0d5813.css (15K -> 3K)
Brotli compressed /home/vagrant/test/test/static/admin/css/base.css (15K -> 3K)
Brotli compressed /home/vagrant/test/test/static/admin/css/base.css (15K -> 3K)
Brotli compressed /home/vagrant/test/test/static/admin/css/base.css (15K -> 3K)
Brotli compressed /home/vagrant/test/test/static/admin/css/changelists.css (6K -> 1K)
Brotli compressed /home/vagrant/test/test/static/admin/css/changelists.css (6K -> 1K)
Brotli compressed /home/vagrant/test/test/static/admin/css/changelists.css (6K -> 1K)
Brotli compressed /home/vagrant/test/test/static/admin/css/changelists.f6dc691f8d62.css (6K -> 1K)
Brotli compressed /home/vagrant/test/test/static/admin/css/changelists.f6dc691f8d62.css (6K -> 1K)
Brotli compressed /home/vagrant/test/test/static/admin/css/changelists.f6dc691f8d62.css (6K -> 1K)
...
```

This is due to a bug in Django's `HashedFilesMixin`, for which I've filed an upstream issue:
https://code.djangoproject.com/ticket/28607

The upstream bug only affects "adjustable files" (ie files that `HashedFilesMixin` has to do a second pass on, in case they cross-reference other files that have been hashed, so might need renaming with a new hash) - which currently is just *.css. However it still has a significant impact on the number of compressions performed:
```
$ grep 'Brotli compressed' collectstatic.log | wc -l
370
$ grep 'Brotli compressed' collectstatic.log | sort -u | wc -l
276
```

Even though this is due to an upstream bug, it would be good to work around it in the meantime.

**Comment by evansd** [comment]
I've got a workaround for this, but the patch still needs a bit of work before I push it up.

**Comment by evansd** [comment]
Finally fixed via this series of commits:
https://github.com/evansd/whitenoise/compare/c3745735677483cb07982a46f3985d35aa3b7647...9e02fa57c0aabd4d8174567f2a9d2ac2e2e21046
