### ISSUE TITLE
Immutability Issue w/ CDN

### ISSUE THREAD

**Issue by lskillen** [evansd/whitenoise#151]
Hello - First of all, thank you for developing and maintaining whitenoise. Making the leap from an S3-based storage to whitenoise proved to solve *many* headaches, and has only introduced some very minor ones in the process. ;-) We love it!

We're currently experiencing an issue with 3.3.0 not being able to determine that a static file is immutable when it actually is. I've done a bit of digging into this and it looks like it's because our public facing URL doesn't have the static prefix in it.

Our setup:

- CDN:
  - Public URL: `https://foo/path/to/asset.abc123.js`
  - Origin URL: `https://foo/static/path/to/asset.abc123.js`

- Django:
  - STATIC_URL: `https://foo/`
  - WHITENOISE_STATIC_PREFIX: `/static/`

[The whitenoise code](https://github.com/evansd/whitenoise/blob/bc8fe1edb7a350607b2d40104d3ce9b8e2e22b16/whitenoise/django.py#L98-L102) that evaluates to the immutability test to False:

```
        # If the static URL function maps the name without hash
        # back to the original URL, then we know we've got a
        # versioned filename
        if static_url and static_url.endswith(url):
            return True
```

I note that the code remains the same on the 4.0 release candidates, so this is probably a good time to reconsider this. It seems like the code should either only be looking at the `basename` for the file when performing the check, or perhaps it should integrate the `WHITENOISE_STATIC_PREFIX` value into the url prior to checking. Thoughts?

This is currently making our production website not cache assets for more than 60 seconds, so we'll probably put *some* sort-of fix in today, but it'd be great to get a permanent fix in too. :-)

Thanks!

*Update1:* We've got a [very simple bugfix available on our fork](https://github.com/cloudsmith-io/whitenoise/commit/aaf3758185129f4e48e4c83759f8271b7dfd5e87). We could turn this into a PR for 4.0 but until it's released a hotfix for 3.3.0 would be fantastic too. :-)

**Comment by evansd** [comment]
Thanks for catching and debugging this. You're absolutely right, it ought to just be comparing the basename.

I should be able to push a 3.3.1 bugfix release at some point this weekend.

**Comment by evansd** [comment]
Here it is: http://whitenoise.evans.io/en/stable/changelog.html

**Comment by lskillen** [comment]
Fantastic - Thank you, and a better approach utilising posixpath as well.
