### ISSUE TITLE
Question about speeding up tests

### ISSUE THREAD

**Issue by oTree-org** [evansd/whitenoise#152]
I have a Django project with about 200 test methods, many of which test my views and loading pages. When I run my Django test suite, it takes 30 seconds to complete. cProfile shows that 9 seconds are spent in `whitenoise.base.add_files` and `whitenoise.base.update_files_dictionary`. 91 calls are made to each of those functions. Is this to be expected with a test suite like mine? Is there a way to speed this up?

My tests already set Django's DEBUG setting to False.

I'm using Django 1.8.8, Whitenoise 3.2.1/3.3.1, and Python 3.6.

**Comment by oTree-org** [comment]
(Correction: 200 test *methods*. Updated my post.)

**Comment by evansd** [comment]
I've added some notes about this in the new version of the docs, which will be released when v4.0 finally gets released.

You can see the preview version here though, hopefully that will help:
http://whitenoise.evans.io/en/latest/django.html#whitenoise-makes-my-tests-run-slow

**Comment by oTree-org** [comment]
That did the trick, thank you!
