### ISSUE TITLE
Recommend Brotli instead of brotlipy?

### ISSUE THREAD

**Issue by edmorley** [evansd/whitenoise#154]
When Brotli support was first added to WhiteNoise, if I remember correctly, the official brotli repo did not yet have its own Python package/bindings. As such, the WhiteNoise docs recommend using [brotlipy](https://pypi.python.org/pypi/brotlipy).

However there's now the official Python package, [Brotli](https://pypi.python.org/pypi/Brotli), which I've been using with WhiteNoise for a while.

Unless there are good reasons to stick with the unofficial bindings, I think we should update the WhiteNoise docs to point people at the `Brotli` package instead.

**Comment by evansd** [comment]
Yes, that makes sense. I assume they're API compatible? -- at least for the tiny bit of the API we use in WhiteNoise.

**Comment by keimlink** [comment]
The APIs of brotlipy and Brotli are very small. AFAICT they're compatible.
