### ISSUE TITLE
Populate `bugtrack_url` from pypi? 

### ISSUE THREAD

**Issue by stig** [evansd/whitenoise#155]
You probably have to do this via the PyPI admin interface :( I've never used the PyPI admin interface, but it should probably be set with a multi-use [Project Url Field](https://www.python.org/dev/peps/pep-0345/#project-url-multiple-use) like so:

`Bug Tracker, https://github.com/evansd/whitenoise/issues`

This should populate the `bugtrack_url` field in https://pypi.python.org/pypi/whitenoise/json -- which in turn lets @dependabot (which I'm not affiliated with, but we use) find that the repo is hosted on GitHub and can in turn find the CHANGELOG file for its automated PRs. This makes it easier for people that use dependabot to view your changelog, and thus reduces friction for us with regards to keeping up with your releases.

**Comment by evansd** [comment]
This seems like a good idea, but I don't see any option to set it through the PyPI admin interface. If someone can give me instructions, or send a PR for setup.py, then I'd happily add this.

**Comment by stig** [comment]
Hi @evansd I've never done this myself, but it appears that it should be set via a `PKG-INFO` file, cf https://www.python.org/dev/peps/pep-0345/#fields -- though I'm not sure whether such a file is  generated by setup.py or not, and I cannot figure out how to get it in there. I asked on [StackOverflow](https://stackoverflow.com/questions/46617605/how-do-you-set-the-bugtrack-url-field-in-pypi-metadata) on the off chance anyone might be able to help.

**Comment by edmorley** [comment]
I believe it cannot be set via setup.py and instead has to be adjusted via the PyPI web dashboard:
pypa/pypi-legacy#581

**Comment by evansd** [comment]
Yeah, I found that ticket but I couldn't see the option anywhere in the PyPI web interface.

**Comment by browniebroke** [comment]
PyPI has now migrated to the new Warehouse project, with a more modern codebase.

At the moment, it looks like this [is hardcoded to `None`](https://github.com/pypa/warehouse/blob/211c43c60aed72db1ace58986cd234d4743fed85/warehouse/legacy/api/json.py#L183) in their API. I guess they left the field for backwards compatibility when they migrated...

Maybe it'll be added back though as in their UI, they do show this information. They do something extra when the `url` in `setup.py` points to [a GitHub URL](https://github.com/pypa/warehouse/blob/b66d92985d42de2b2554ff7872ce4723860e1bd5/warehouse/packaging/models.py#L395-L403), which adds [a new section in the sidebar](https://github.com/pypa/warehouse/blob/f9a59bac130bbfa3932ed2c8a3b1908578a82aea/warehouse/templates/includes/packaging/project-data.html#L31-L56).

**Comment by adamchainz** [comment]
The project metadata now includes links to the home (github), docs, and changelog directly: https://github.com/evansd/whitenoise/blob/8ea1336bdd5c6586ab2cbd99930653be80dca18e/setup.cfg#L10-L12

So I think this is all taken care of.
