### ISSUE TITLE
PATH_INFO is optional

### ISSUE THREAD

**Issue by davidszotten** [evansd/whitenoise#156]
Just had a request throw a `KeyError` from `WhiteNoise.__call__` https://github.com/evansd/whitenoise/blob/master/whitenoise/base.py#L68 when getting `PATH_INFO` from the environment. 

Was trying to figure out if the issue was the server (uwsgi) or whitehoise. From reading the wsgi pep it seems the key is optional when the value is a blank string, so maybe whitenoise should handle this?

**Comment by davidszotten** [comment]
thanks!

**Comment by evansd** [comment]
Trying to clear the backlog finally :smile:
