### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by scotu** [evansd/whitenoise#161]
Hi, 

I have a couple of questions about the status of django 1.11 support:

* I see that the v4 beta adds explicit support for it and I was wondering if there is a timeline for a final release
* I can't see any open issues raised about 1.11 support and wonder if anybody is running on 1.11 successfully with the latest stable release

thanks for your answers and for the work on whitenoise!

**Comment by evansd** [comment]
Yes, the stable release works fine with Django 1.11. I'm using it in production myself on several applications.
