### ISSUE TITLE
WhiteNoise integration with Flask

### ISSUE THREAD

**Issue by fernandobohrer** [evansd/whitenoise#165]
Hi there,

I've followed the Flask basic startup guide and tried to integrate my Flask app with WhiteNoise. After changing the app configuration as the WhiteNoise documentation suggests, wheneaver I try to run the app, the following error shows up:

```
(.venv) bohrer@1VCS442 ~/dev/flask_experiment/flask_experiment $ python app.py 
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    @app.route('/')
AttributeError: 'WhiteNoise' object has no attribute 'route'
```
The code is available here: https://github.com/fernandobohrer/flask_experiment/blob/master/flask_experiment/app.py

**Comment by edmorley** [comment]
Hi!

The docs on setting up Flask with WhiteNoise were incorrect until recently (#158). That PR isn't yet on the `stable` branch of the docs, but can be seen on `latest`, here:
http://whitenoise.evans.io/en/latest/flask.html#enable-whitenoise

(The key part is making sure to only wrap `app.wsgi_app` and not all of `app`)

Hope that helps :-)

**Comment by fernandobohrer** [comment]
Hi there,

It worked perfectly! Thanks!

**Comment by chhantyal** [comment]
Looks like wrapping `wsgi_app` is actually not working.

My setting is: `app.wsgi_app = WhiteNoise(app.wsgi_app, root='static/')`

However, Flask is not using WhiteNoise at all and serves from default static server. 
You can see that from response header:

```
Accept-Ranges:bytes
Cache-Control:public, max-age=43200
Connection:close
Content-Length:11772
Content-Type:text/css; charset=utf-8
Date:Fri, 02 Feb 2018 15:03:07 GMT
ETag:"1517560254.0-11772-2491291194"
Expires:Sat, 03 Feb 2018 03:03:07 GMT
Last-Modified:Fri, 02 Feb 2018 08:30:54 GMT
Server:gunicorn/19.7.1
```
