### ISSUE TITLE
Whitenoise processes references in comments

### ISSUE THREAD

**Issue by Folcon** [evansd/whitenoise#167]
```
whitenoise.storage.MissingFileError: The file 'vendor/css/bootstrap/less/variables.less' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x1069b25c0>.

The CSS file 'vendor/css/re-com.css' references a file which could not be found:
  vendor/css/bootstrap/less/variables.less

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

Even though the references are in the comments, whitenoise processes it.

I don't believe this is correct behaviour?

Note: I've added the txt extension to get github to allow attaching it.
[re-com.css.txt](https://github.com/evansd/whitenoise/files/1594538/re-com.css.txt)

**Comment by evansd** [comment]
Unfortunately this is a bug with Django, and not one that WhiteNoise can fix. See https://github.com/evansd/whitenoise/issues/58
