### ISSUE TITLE
Document storage backend requirements for compatibility

### ISSUE THREAD

**Issue by thenewguy** [evansd/whitenoise#17]
It would be helpful to add the requirements of the storage backend that whitenoise uses to the documentation for subclassing.  For example, does it require that the storage backend supply a local file path, or could it use a remote storage backend?

**Comment by thenewguy** [comment]
I am embarrassed to say this bit me again

**Comment by evansd** [comment]
@thenewguy And I'm embarrassed I've let this issue languish so long ;) Partly, though, this is because you're the only person who's ever asked about this and I don't quite understand your use case.

Why do you want to store your static files remotely only to transfer the data back locally to serve it via WhiteNoise?

**Comment by thenewguy** [comment]
@evansd Hey no problem. The staticfiles are collected and compressed during build phase and stored in an s3 bucket.  The application is deployed on ec2.  It is more trouble to coordinate local access filesystem access to the files than it is to proxy them.  Doing it this way also allows serving static files from previous versions until they are no longer requested by older clients and then the files are purged.  It also simplifies caching because the contents in the s3 bucket are not all public and as such the s3 urls must be signed.  The signature prevents long term caching.

**Comment by evansd** [comment]
@thenewguy I think your use case is rare enough that it's not something core WhiteNoise should support.

Obviously you know the details of your requirements better than I do, but it seems like there are two approaches you could take. One would be to run `collectstatic` as part of the build phase and have the resulting files included with the rest of the build artifacts. The other would be to set a public acl and the appropriate cache headers on the individual files when they're uploaded to S3. It doesn't matter that the bucket as a whole isn't public: individual files within it can still be marked public so you don't need to use signed URLs.

**Comment by thenewguy** [comment]
@evansd No problem.  The check is a good idea.  But the "location" attribute doesn't indicate that the storage is local.  Here is a commonly used S3 storage backend that uses location https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L217  I think you would need to use the path() method https://docs.djangoproject.com/en/1.9/ref/files/storage/#django.core.files.storage.Storage.path

**Comment by evansd** [comment]
Ah crap! Thanks for pointing that out.

I thought about using `path()` but I think I then need the name of an existing file to pass into it, which complicates things a bit.

Another solution might be to compare the values of `location` and `STATIC_ROOT`. In a correctly configured set up they should point to the same place.
