### ISSUE TITLE
Some files 404ing in WHITENOISE_ROOT on Heroku

### ISSUE THREAD

**Issue by philgyford** [evansd/whitenoise#170]
I'm using `WHITENOISE_ROOT` to serve some HTML/image files and it's mostly working wonderfully.

But a few files 404 on the site on Heroku (they're fine on my local Vagrant version) and I can't work out why they fail.

e.g. http://www.gyford.com/japanese/ (index.html) works fine but http://www.gyford.com/japanese/icons/favicon.ico and http://www.gyford.com/japanese/icons/apple-touch-icon.png both 404.

And while http://www.gyford.com/misc/askjeeves/ (index.html) works http://www.gyford.com/misc/mappiness/ (index.html) 404s.

I can't see what's different about the working and non-working files. My settings are:

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # ...
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(APPS_DIR, 'static_collected/')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(APPS_DIR, 'static'),
]

WHITENOISE_ROOT = os.path.join(APPS_DIR, 'static_html/')

WHITENOISE_INDEX_FILE = True
```

`/japanese/` and `/misc/` are both within the `static_html` directory.

**Comment by evansd** [comment]
That's really strange! You've checked the obvious stuff e.g. that the files are actually committed to git?

**Comment by philgyford** [comment]
> You've checked the obvious stuff e.g. that the files are actually committed to git?

You'd think someone would check something that obvious first wouldn't you...

You're right! And I'm an idiot! :)

git was quietly failing to include them. The `japanese/icons/` directory was quietly ignored by git because I had `Icon?` in my `.gitignore_global` and there was some oddness going on that made git think the `/mappiness/` directory was a git submodule.

Thanks for the extra pair of eyes.

**Comment by evansd** [comment]
:) No probs; glad it works now.
