### ISSUE TITLE
Dry run with whitenoise

### ISSUE THREAD

**Issue by ChaosCA** [evansd/whitenoise#175]
Hey @evansd, I just had a question I couldn't find an answer to in the docs.

Does whitenoise still fail if a static file is missing in a reference while running `collectstatic --dry-run`? According to the Django docs it says it does everything except file operations.

I wanted to run this on my build server to make sure there are no missing references prior to deploying but running without the dry-run is expensive and time consuming on a build server.

Thank you!

**Comment by evansd** [comment]
Just checking the Django source, it looks like it doesn't do any post-processing in `dry-run` mode:
https://github.com/django/django/blob/stable/2.0.x/django/contrib/staticfiles/storage.py#L225

You'll need to do the full collectstatic at some point during the build anyway. I don't know how your deploy pipeline is set up, but maybe there's a way to avoid having to do it twice.
