### ISSUE TITLE
whitenoise throws errors on css files which contain urls in comments

### ISSUE THREAD

**Issue by guyjacks** [evansd/whitenoise#182]
I'm pretty certain that its a bug in Django, but I'm posting here because it really only matters if you're using Whitenoise.

This a critical issue, because this bug prevents deploying a Django app to Heroku if you're using whitenoise and your app depends on a css file with commented urls.  Heroku doesn't provide any hooks that allow us to remedy this before collectstatic runs via some kind of shell script.  

The only solution would be to prebuild the assets and include them in the repo and then remove any reference to css files with commented urls.  This is obviously not ideal.

Whitenoise has been great, but we have tried everything we can think of and are likely going to have to use s3 for our static assets.  We've modified the NPM package so that it provides a minified css file without comments, but collectstatic still collects the other css file.  We've tried Heroku hooks, but collectstatic runs before they do.  A solution that will work is to manually store the files we need in the npm package and remove the npm package, but that's hacky.  Do you guys have any suggestions for how to get around this issue?

Here's the bug in Django: https://code.djangoproject.com/ticket/21080#comment:7  Its five years old and for whatever reason the Django team has not prioritized resolving it.

You're help would be greatly appreciated.  Maybe you could convince the Django team that is an issue of strategic importance, because it essentially makes deploying django apps with modern javascript dependencies to Heroku very difficult.  Whitenoise makes Heroku + Django make sense.  Thanks.

**Comment by evansd** [comment]
Your best option might be to [disable](https://devcenter.heroku.com/articles/django-assets#disabling-collectstatic) Heroku's automatic collectstatic behaviour and then create your own `bin/post_compile` script which runs collectstatic after doing whatever hacks you need to get things working. Not the nicest solution but might be the fastest fix for now.

**Comment by joshua-s** [comment]
Thanks @evansd!

**Comment by adilnaimi** [comment]
I'm having the same issue, I can collect Django static file on my local machine and also on my own server without any issue, I think this might be related to whitenoise or the Heroku why how it looks to staticfiles but definitely not Django, I'm not having any issue with Django itself

**Comment by edmorley** [comment]
@adilnaimi hi! This issue is about ways to work around something that is definitely a Django bug. Perhaps your issue is different? Have you tried comparing the result using the WhiteNoise storage backend to the stock Django `` backend to rule out issues with the latter? See:
http://whitenoise.evans.io/en/stable/django.html#troubleshooting-the-whitenoise-storage-backend

Alternatively I'd check that your environments are deterministic (eg all packages including transient dependencies pinnned).
