### ISSUE TITLE
Allow multiple roots

### ISSUE THREAD

**Issue by aeby** [evansd/whitenoise#183]
Would it make sense/is a PR welcome to allow multiple "root" folders in the Django middleware? Right now the files in the directory specified by `WHITENOISE_ROOT` is served at `/`. I think of a setting like this:

```
# Keep this setting for backward compatibility
WHITENOISE_ROOT = os.path.join(BASE_DIR, 'if/dist')

# Roots as tuples of <DIRECTORY>, <PREFIX> 
WHITENOISE_ROOTS = (
    (<MY_OTHER_DIR>, '/other/'),
    (<MY_PWA_DIR>, '/pwa/')
)
```
In [middleware.py](https://github.com/evansd/whitenoise/blob/master/whitenoise/middleware.py#L41) we could allow other roots with something like this:

```
for root in self.roots:
    add_files(*root)
```
The motivation behind are PWA with service workers that need to be served from a specific directory due to scoping. If I have for example an app running at /pwa i have to serve its service worker from this directory.

**Comment by evansd** [comment]
You should be able to handle this already by just creating `other` and `pwa` directories inside the WHITENOISE_ROOT directory.

If you want the files for these to live some outside of the root directory you can use relative symlinks.

**Comment by aeby** [comment]
You are completely right - thanks for the fast reply. Just for the record in case symlinks don't work for someone: You can implement your own middleware quite easily:

```
from django.conf import settings
from whitenoise import WhiteNoise
from whitenoise.middleware import WhiteNoiseMiddleware

class MyWhiteNoiseMiddleware(WhiteNoiseMiddleware):
    config_attrs = WhiteNoise.config_attrs + (
        'root', 'roots', 'use_finders', 'static_prefix')

    roots = []

    def __init__(self, get_response=None, settings=settings):
        super(MyWhiteNoiseMiddleware, self).__init__(get_response, settings)
        for r in self.roots:
            self.add_files(*r)
```
