### ISSUE TITLE
Is there a way to tell WhiteNoise to ignore missing files

### ISSUE THREAD

**Issue by inikolaev** [evansd/whitenoise#184]
We are using a library `bootstrap-formhelpers`, but CSS is referencing images which do not exist. 

I found a similar issue here https://github.com/tenex/rails-assets/issues/150 and wonder if there's some option in WhiteNoise which allows to ignore missing files and pretend that files are actually there without crashing?

**Comment by evansd** [comment]
There's no option to do this (it's just the behaviour of the underlying Django library which WhiteNoise doesn't change) but you could probably subclass the storage backend and hack this behaviour in if you really wanted.
