### ISSUE TITLE
Add webroot support

### ISSUE THREAD

**Issue by astronouth7303** [evansd/whitenoise#187]
The combination of gunicorn, whitenoise, django, and certbot (Let's Encrypt) is somewhat annoying.

I kinda really like the usability of gunicorn+whitenoise, leaving out nginx, apache, etc.

Can an option or standard configuration be added so that whitenoise can serve a certbot-controlled webroot, so that you can somewhat easily get certificates for gunicorn?

**Comment by evansd** [comment]
WhiteNoise already has a [webroot feature](http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_ROOT) and you can use symlinks from within the webroot if you want to serve files from arbitrary locations.

The difficulty will be that in production mode, WhiteNoise only checks for files once on startup and won't pick up new files that certbot creates after the process has started. Maybe you could work around this by just restarting your app after certbot does its thing?
