### ISSUE TITLE
Test failure under Python 2.7

### ISSUE THREAD

**Issue by felixonmars** [evansd/whitenoise#189]
The latest 4.0 release passes the tests here under Python 3.7, but has one test failure under Python 2.7:

```
=================================== FAILURES ===================================
__________ WhiteNoiseAutorefresh.test_warn_about_missing_directories ___________

self = <tests.test_whitenoise.WhiteNoiseAutorefresh testMethod=test_warn_about_missing_directories>

    def test_warn_about_missing_directories(self):
        with warnings.catch_warnings(record=True) as warning_list:
            self.application.add_files(u'/dev/null/nosuchdir\u2713')
>       self.assertEqual(len(warning_list), 1)
E       AssertionError: 0 != 1

tests/test_whitenoise.py:208: AssertionError
=============================== warnings summary ===============================
tests/test_django_whitenoise.py::TestServer
  cannot collect test class 'TestServer' because it has a __init__ constructor

tests/test_whitenoise.py::TestServer
  cannot collect test class 'TestServer' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=============== 1 failed, 90 passed, 2 warnings in 0.83 seconds ================
```

**Comment by evansd** [comment]
It looks like you're running the tests using pytest, rather than `python -m unittest discover` which is what tox and the CI runner are using. Pytest captures warnings by default which is probably interfering with the test here and triggering the failure.

You could try [disabling](https://docs.pytest.org/en/latest/warnings.html#disabling-warning-capture) pytest's warning capture and see if that makes a difference.

Long term it would be great to move the test suite over to use pytest as it's so much nicer than the built in unittests, but that's not going to happen anytime soon.

**Comment by felixonmars** [comment]
Looks like it's not related :/

I have tried to run the test suite with `python -m unittest discover`/Python 2.7 but got exactly the same error:

```
======================================================================
FAIL: test_warn_about_missing_directories (tests.test_whitenoise.WhiteNoiseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-whitenoise/src/whitenoise-4.0-py2/tests/test_whitenoise.py", line 208, in test_warn_about_missing_directories
    self.assertEqual(len(warning_list), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 91 tests in 0.333s

FAILED (failures=1)
```

It works fine under Python 3.7 though.

**Comment by felixonmars** [comment]
I think I found the issue - I missed the "PYTHONWARNINGS=all" environment variable. Sorry for the false positive!

**Comment by evansd** [comment]
Ha! Was just coming here to point that out :)

No worries. Out of interest, how come you're not running the tests using tox anyway?

**Comment by felixonmars** [comment]
I am packaging whitenoise for Arch Linux, and we would like to avoid network access and sandbox techniques in the build environment if possible :P
