### ISSUE TITLE
Document the fact that modifying files at runtime won't work with WhiteNoise

### ISSUE THREAD

**Issue by evansd** [evansd/whitenoise#19]
Make it clear that WhiteNoise is for serving fixed sets of static files in production. And suggest workarounds/alternatives for serving files in development.

**Comment by sawall** [comment]
As a data point, I also ended up here because I was trying to figure out why I couldn't get django-compressor to play nicely with WhiteNoise.

**Comment by mikob** [comment]
Just want to chime in, django file uploads (a core part of django) won't work because of the aforementioned facts.

**Comment by edmorley** [comment]
An alternative might be [RedNoise](https://github.com/ryanmcgrath/django-rednoise/) - though not sure how well it works fwiw.

**Comment by evansd** [comment]
WhiteNoise v2.0 now supports this via the `autorefresh` setting, although it's only explicitly supported as a development feature so use in production at your at risk.
