### ISSUE TITLE
Using CompressedStaticFilesMixin by itself doesn't seem to work

### ISSUE THREAD

**Issue by toolness** [evansd/whitenoise#194]
Hi, for various complicated reasons I couldn't use the manifest-based static file storage, but I _did_ want gzip/brotli compression, so I thought I could use the [`CompressedStaticFilesMixin`](https://github.com/evansd/whitenoise/blob/master/whitenoise/storage.py) for that, since the documentation says:

```
Wraps a StaticFilesStorage instance to create compressed versions of its
output files and, optionally, to delete the non-hashed files (i.e. those
without the hash in their name)
```

So I tried creating a trivial subclass of `StaticFilesStorage` that simply mixed-in `CompressedStaticFilesMixin`:

```python
class CompressedStaticFilesStorage(CompressedStaticFilesMixin, StaticFilesStorage):
    pass
```

However, running `collectstatic` with this storage backend then raised the following error:

```pytb
Traceback (most recent call last):
...
  File "...\lib\site-packages\whitenoise\storage.py", line 23, in post_process
    files = super(CompressedStaticFilesMixin, self).post_process(*args, **kwargs)
AttributeError: 'super' object has no attribute 'post_process'
```

I was then very confused because the [Django documentation](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.StaticFilesStorage.post_process) says that this `post_process` method actually _should_ exist, but it doesn't, so I filed https://code.djangoproject.com/ticket/29677.

In any case, after much fumbling, I managed to write this, which seemed to work:

```python
from django.contrib.staticfiles.storage import StaticFilesStorage
from whitenoise.compress import Compressor

class CompressedStaticFilesStorage(StaticFilesStorage):
    def post_process(self, paths, **options):
        compressor = Compressor()
        for path in paths:
            if compressor.should_compress(path):
                abspath = self.path(path)
                for compressed_path in compressor.compress(abspath):
                    yield path, compressed_path, True
```

I'm not really sure if I'm iterating the right values (the documentation for Django's `post_process` is not very informative on this).  But if it's useful to folks who want more of a middle ground between "serve static assets uncompressed" and "serve static assets with compression _and_ hash their filenames" then I could issue a PR, if that helps.

**Comment by evansd** [comment]
Hi, thanks for reporting this. Having looked at this a bit more closely now, I think the class I've created isn't really a mixin anymore as it's become too dependant on specific implementation details of the ManifestStaticFilesStorage class.

So I'll think I'll move it to being a subclass of ManifestStaticFilesStorage and then replace it with a much simpler class which genuinely is a mixin and doesn't try to do anything clever.

**Comment by toolness** [comment]
Oh awesome, that sounds great!
