### ISSUE TITLE
Potential Path Traversal in Windows

### ISSUE THREAD

**Issue by phith0n** [evansd/whitenoise#197]
I saw that WhiteNoise use following function to check the path traversal attack:

```python
@staticmethod
def url_is_canonical(url):
    """
    Check that the URL path does not contain any elements which might be
    used in a path traversal attack
    """
    if '\\' in url:
        return False
    normalised = normpath(url)
    if url.endswith('/') and url != '/':
        normalised += '/'
    return normalised == url
```

In Windows, we can use absolute path to bypass the checker, like `/static/C:/windows/win.ini`.

A example application:

```python
from wsgiref.simple_server import make_server, demo_app
from whitenoise import WhiteNoise

application = WhiteNoise(demo_app, root='static/', prefix='static/', autorefresh=True)
httpd = make_server('', 8000, application)
httpd.serve_forever()

```

Path traversal and downloading `C:/windows/win.ini`:

![image](https://user-images.githubusercontent.com/5711185/45491544-880af200-b79c-11e8-9f9d-29fc89b3f2bf.png)

**Comment by evansd** [comment]
Excellent catch! Thank you. This is exactly why I tell people not to use "autorefresh" in production :smile: 

It looks like a better way of preventing directory traversal is to join the paths and then use `os.path.commonprefix` to check that the result is contained in the original directory. I'll make a patch for that shortly.

**Comment by phith0n** [comment]
I'm honored to help you to improve whitenoise. 😄

**Comment by hartwork** [comment]
:+1: on `os.path.commonprefix` ([example use in `django-directory`](https://github.com/ASKBOT/django-directory/blob/master/directory/views.py#L41))
