### ISSUE TITLE
Invalidate outdated browser cache when version changes

### ISSUE THREAD

**Issue by fabiocaccamo** [evansd/whitenoise#200]
It would be nice to have the possibility to avoid browser caching only when **file version** changes.

`{% static "path/to/app.js" cache_version=True %}` -> `/static/path/to/app.js?version=1.1`

Is it possible to do that?

**Comment by evansd** [comment]
Hi,

Django already provides this behaviour with the ManifestStaticFilesStorage backend. See:
https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
http://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support

**Comment by fabiocaccamo** [comment]
@evansd thanks! I missed it...
