### ISSUE TITLE
Docs build failing?

### ISSUE THREAD

**Issue by adamchainz** [evansd/whitenoise#209]
http://whitenoise.evans.io/en/stable/changelog.html doesn't feature 4.1.2 but I see it was added in 8a374b49fb4bf8e17af4d51f3bfabb3e08d783a8, perhaps readthedocs is failing? I know I've missed it failing in the past on my own projects.

**Comment by evansd** [comment]
Thanks for spotting this! I just forced a rebuild on readthedocs and now it's updated correctly. RTD seems to be pretty flaky these days. I'll try to remember to double check this when I publish new versions.

**Comment by adamchainz** [comment]
🎉 Thanks! 🌈
