### ISSUE TITLE
Request to re-examine issues raised in #163

### ISSUE THREAD

**Issue by MalikRumi** [evansd/whitenoise#210]
You closed #163 for lack of a response from the OP. I am having a similar issue and have spent a week on it without resolution. There are numerous unresolved posts on SO about similar issues. This one describes my situation the closest: https://stackoverflow.com/questions/46713538/cant-make-whitenoise-work-with-django-heroku-for-production. 

With debug=True, it works. With debug=False, it comes up 500. It is the same with or without the django-heroku package https://github.com/heroku/django-heroku, which according to the Heroku docs, is supposed to 'just work': https://devcenter.heroku.com/articles/django-app-configuration.

Heroku does not offer much support for application issues, and the last word I got from them was that, on top of that, they are suffering through a kind of 'Christmas rush' which pushes these issues further back from attention. 

I have upgraded to whitenoise v4+, edited wsgi.py, and added the whitenoise middleware. I am attaching a version of my settings with sensitive stuff omitted. I am also attaching a copy of wsgi.py. Ignore the reference to Django 1.7, I'm on 1.11.6. You can tell from the comments some of the variations I have already tried. I don't know what else to do.
[wsgi.txt](https://github.com/evansd/whitenoise/files/2696429/wsgi.txt)
 
[edited_settings_for_whitenoise_github_issues.txt](https://github.com/evansd/whitenoise/files/2696411/edited_settings_for_whitenoise_github_issues.txt)

**Comment by evansd** [comment]
The only thing that leaps out at me as obviously incorrect in your settings is this line:
```python
STATICFILES_DIRS = ('/home/malikarumi/Projects/aishah/jamf35/static/',)
```
This reference to an absolute path on your local filesystem will definitely not work on Heroku.

The line you've commented out looks better:
```python
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
```

If you can provide me with the URL to a complete project which reproduces the problem then I can investigate further. But without that I can't do any more.

I would suggest trying a couple of things:

1. Run your project locally using `DEBUG = False` and check that everything works as expected.

2. Try to get the simplest possible Django project deployed and working with static files. For example, a project with a single HTML page which loads a single CSS file. Start with a new empty project and add things piece by piece, checking that you can deploy it successfully to Heroku at each stage. You can then try copying over the more complex parts of your real project, one step at a time, until it stops working. You will probably find that if you do things in this way then the problem becomes obvious.

**Comment by MalikRumi** [comment]
I figured it out, and posted the solution to SO here
https://stackoverflow.com/questions/51110020/django-valueerror-missing-staticfiles-manifest-entry-for-inline-bundle-js-run/53876443#53876443
in case anyone else comes along with similar issues. Thanks.

*“None of you has faith until he loves for his brother or his neighbor what
he loves for himself.”*

**Comment by Liamhanninen** [comment]
This was an issue for me as well. I fixed it using that solution - but like that comment suggested it disables some feature. So hopefully this gets corrected. I have no idea what the solution would be but I certainly would not consider this closed or at least 'solved'.
