### ISSUE TITLE
`Content-Type` header not set for request of gzipped file

### ISSUE THREAD

**Issue by cph2117** [evansd/whitenoise#211]
I've implemented Whitenoise in a Django/gunicorn/heroku project following the instructions:
`settings.py`
```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
   # ...
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```
I have a static `index.html` file that contains a script `<script src="/static/js/main.25c49024.chunk.js.gz"></script>`. When the page loads it throws a console error: `Uncaught SyntaxError: Invalid or unexpected token`. Presumably it's because the browser doesn't recognize how to decode the file b/c the response headers don't indicate that it's a gzip file: 
<img width="288" alt="screen shot 2018-12-25 at 2 31 39 pm" src="https://user-images.githubusercontent.com/6933080/50426032-19850800-0852-11e9-8831-f4ba8870d918.png">

What am I missing here?

**Comment by evansd** [comment]
You shouldn't request the `.gz` file directly. Your URL should be `/static/js/main.25c49024.chunk.js` instead, and then the `Accept-Encoding` header of the browser will determine which compressed variant gets served.

**Comment by cph2117** [comment]
Thanks for the quick response, @evansd . The browser is sending the `Accept-Encoding` header with the request, but it the gzipped version of the file isn't served.
<img width="324" alt="screen shot 2018-12-26 at 2 53 34 pm" src="https://user-images.githubusercontent.com/6933080/50455770-37b83a00-091e-11e9-9198-618d47400421.png">

**Comment by evansd** [comment]
You need to remove the `.gz` from the end of the URL
