### ISSUE TITLE
Django 2.1.7 is not compatible with whitenoise

### ISSUE THREAD

**Issue by dkliban** [evansd/whitenoise#213]
Our application uses whitenoise to serve static content. After upgrading Django to 2.1.7 I started seeing the following errors in our logs.

```
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/style.css
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/insQ.min.js
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/url-polyfill.min.js
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/redoc-init.js
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/redoc/redoc.min.js
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/url-polyfill.min.js
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/redoc-init.js
Feb 28 14:42:05 ... gunicorn[15681]: pulp: django.request:WARNING: Not Found: /static/drf-yasg/redoc/redoc.min.js```


Downgrading to Django 2.1.5 fixes the problem.

**Comment by evansd** [comment]
I don't think there's any incompatibility here: the tests pass fine on Django 2.1.7 and there's nothing in the release notes for either 2.1.7 or 2.1.6 that's at all relevant to WhiteNoise.

I suspect you've got some other issue with your configuration here. If you can give me any more info I might be able to help debug it.

**Comment by dkliban** [comment]
Here[0] is the settings.py ... the static root is set on line 19 and the middleware is list on line 93. 


[0] https://paste.fedoraproject.org/paste/6Me0Yg5sSS~OMDzDo~H7yg

**Comment by evansd** [comment]
Your settings all look OK.

I'm still pretty sure it won't be an compatibility bug though. Maybe you didn't run collectstatic or something after upgrading?

If you can provide a repo which reliably demonstrates the issue I'll take a look.

**Comment by dkliban** [comment]
You are right. I was not restarting the web server after running collect static. Sorry about the bad bug report.
