### ISSUE TITLE
HTML5 History Mode for static site: rewrite engine support

### ISSUE THREAD

**Issue by GabLeRoux** [evansd/whitenoise#214]
Hello there,  
whitenoise is a very handy project, I've been using this for a while and it works very well, thanks :tada:

So here it is; I plan to do use a setup that looks like this:  
1. API served on example.com/api
2. Static site served on example.com/
3. Static site will use the api as one would expect

Frontend is currently built using `vue-js` I'd like to use vue's HTML5 History Mode. I've enabled `WHITENOISE_INDEX_FILE`, set `STATIC_URL` to `/` and prefixed all my django urls with `api/`.

This works fine, but I'd like to also use the [`vue-router`'s `HTML5 History Mode` documentation](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations).

Here's the current behaviour:
1. home page
![image](https://user-images.githubusercontent.com/1264761/53960697-f5953c80-40b4-11e9-85fc-5174e798fadd.png)
2. Click on login (using vue-router)
![image](https://user-images.githubusercontent.com/1264761/53960715-ff1ea480-40b4-11e9-92fc-074b1c3b9038.png)
3. Refresh the page
![image](https://user-images.githubusercontent.com/1264761/53960742-0d6cc080-40b5-11e9-99ca-a34c2d6dda2d.png)

In [`vue-router`'s `HTML5 History Mode` documentation](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations), they provide a few examples to configure web servers such as nginx, apache, caddy, firebase, etc. In the case of Nodejs, I would have used something like [bripkens/connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback/). I'm wondering if there could be a quick way to achieve this with withenoise.

_I'm asking here, but I may end up configuring two different subdomains and let caddy or any web server serve the static site as rewrite rules are easy to apply there._

**Comment by GabLeRoux** [comment]
If using cloudfront, I guess it would work by following something like [How to enable history mode for AWS S3 hosted Vue applications](https://medium.com/@BjornKrols/how-to-enable-history-mode-for-aws-s3-hosted-vue-applications-3bf40d51d9a7).

**Comment by evansd** [comment]
Glad WhiteNoise is useful for you.

I would handle this in Django `urls.py` by adding something like the following code:

```python
# ...
from django.http import FileResponse
# ...

urlpatterns = [
    #  ...
    # This must go at the bottom of urlpatterns, after all your API views
    path('<path:path>/', index_view),
]

def index_view(request, path):
    return FileResponse(open('/path/to/index.html', 'rb'))
```
