### ISSUE TITLE
disable caching for static files matching a pattern

### ISSUE THREAD

**Issue by satyanash** [evansd/whitenoise#216]
What is the recommended way to control caching for static files that match a pattern?
For example:
*  the browser should never cache all my `index.html` files (`max-age=0`). 
*  the browser should cache forever all paths starting with `static/foo` as these are already generated by $LATEST_JS_THING and have a unique hash in their name.
* Any file that does not match above patterns should have the configured `max-age` as it does already.

**Comment by satyanash** [comment]
One way to implement this would be to use the `WHITENOISE_ADD_HEADERS_FUNTION` as follows:

```python
import re

cache_forever = re.compile("\\.[a-f0-9]{5,}\\.((min|bundle)\\.)?(js|css)$")
cache_never = re.compile("\\.html$")

def whitenoise_add_header(headers, path, url):
    if cache_never.search(path):
        print("caching {} never".format(url))
        headers["Cache-Control"] = "max-age=0, public"
    elif cache_forever.search(path):
        print("caching {} forever".format(url))
        headers["Cache-Control"] = "max-age=86400, public, immutable"

WHITENOISE_ADD_HEADERS_FUNCTION = whitenoise_add_header
```

**Comment by evansd** [comment]
If you really need three different cache ages then I think your suggestion above is the easiest way to handle this.

If you can live with having cache lifetimes of just zero and forever then you can do it more easily using the [IMMUTABLE_FILE_TEST](http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_IMMUTABLE_FILE_TEST) setting, which can take a regex string:
```python
WHITENOISE_IMMUTABLE_FILE_TEST = r"\.[a-f0-9]{5,}\.((min|bundle)\.)?(js|css)$"
```
