### ISSUE TITLE
OPTIONS HTTP request support

### ISSUE THREAD

**Issue by craigruks** [evansd/whitenoise#22]
Currently whitenoise only allows GET and HEAD HTTP requests. If you put a CDN in front of whitenoise and attempt to GET an asset across domains, the browser send a preflight ORIGINS HTTP request first, to see if it can then GET the asset. Therefore it would be nice to have the ORIGINS HTTP request permitted as well.

**Comment by gavinwahl** [comment]
I'm encountering this issue when using require.js. It fetches static assets with jQuery, which adds the X-Requested-With header, which triggers a preflight OPTIONS request.

**Comment by evansd** [comment]
I'm surprised by this as [by default](https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/ajax/xhr.js#L59) jQuery doesn't set `X-Requested-With` on cross-origin requests.

If you can post a link to a reproducing example perhaps I can help spot the problem.

In any case, I think this is a client error and not an issue with WhiteNoise.

**Comment by gavinwahl** [comment]
@evansd You are right. A library I'm using was doing something stupid (calling `$.ajaxSetup({crossDomain: false})` (fusionbox/django-widgy#374)). Thanks for the pointer.
