### ISSUE TITLE
Using Whitenoise with Cloudflare's CDN

### ISSUE THREAD

**Issue by subodh-malgonde** [evansd/whitenoise#220]
I have transferred my domain's nameservers to Cloudflare, which provides CDN services  along with it. 

I just want to confirm my understanding of using Cloudflare's CDN when managing static files with Whitenoise:

1. The docs contain instruction for setting up Whitenoise with Cloudfront. I am using Cloudflare and unlike Cloudfront it does not provide a CDN subdomain or host name. See this [Does Cloudflare provide me with a CDN subdomain or hostname?](https://support.cloudflare.com/hc/en-us/articles/203689034-Does-Cloudflare-provide-me-with-a-CDN-subdomain-or-hostname-).
2. Cloudflare decides caching time based on file extensions and caching headers. See this [How Do I Tell Cloudflare What to Cache?](https://support.cloudflare.com/hc/en-us/articles/202775670). 

Since the headers are handled effectively by Whitenoise, I don't need to change anything in my Django settings (like setting static host when using Cloudfront) or change any settings in Cloudflare's dashboard. Am I right?

**Comment by evansd** [comment]
Yes, that's right. With Cloudflare everything should work correctly without any extra configuration.
