### ISSUE TITLE
WhiteNoise storage doesn't serve my static files

### ISSUE THREAD

**Issue by alexanderisora** [evansd/whitenoise#221]
Hello! I'm using Whitenoise in my Django application running on Heroku.

I've faced a problem and stumbled this post:
http://whitenoise.evans.io/en/stable/django.html#troubleshooting-the-whitenoise-storage-backend

When I set 
`STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'` 
my static files are loaded well.
But when it is
`STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'` 
the static is not loaded properly.

Some more info on the problem:
I have 2 static files folders type:
1) CSS and JS files created by me. They are named like this `my_styles.css` and changed only manually by me.
2) CSS and JS files created by Webpack (create-react-app). They are named like this `main.a17463f1.chunk.js`. These files are generated by Webpack during a build.

Problem: static files of type 1) are loaded every time - even with the whitenoise storage enabled. But files of the type 2) are NOT loaded with the whitenoise storage backend.

Is this because of the hashes in the files' titles? 
If so, does anyone have experience with serving the generated hashed static files with whitenoise?

**Comment by evansd** [comment]
Hi @alexanderisora, the easiest way to debug this would be if you could link to an example repo which reproduces the problem. Obviously you might not want to make you entire project public but if you can strip it down to just what's needed to demonstrate the problem then that would be really helpful.

Other than that, I wonder if the problem is something to do with the webpack build step. How exactly does this get run? And does it definitely happen before `collectstatic ` is run?

WhiteNoise shouldn't have any issue serving files with hashes in their name. There's some extra logic around caching headers for files hashed using Django's system, but that shouldn't affect your webpack files and even if it did it wouldn't stop them from being served.

**Comment by alexanderisora** [comment]
Hello @evansd and thanks for your reply!

> Obviously you might not want to make you entire project public but if you can strip it down to just what's needed to demonstrate the problem then that would be really helpful.
Unfortunately, I can not share the whole code. Though, I can share some parts. 
Sorry, but I don't understand what exactly do you want to see? I also can perform any debug tests you ask me to do.

>How exactly does this get run? 
The webpack config is default [CRA](https://facebook.github.io/create-react-app/) without `npm eject`. Just a little TypeScript tuning via [React-app-rewired](https://github.com/timarney/react-app-rewired). I run `yarn build` and it produces the `/build` folder with files which contain hashes in its name: https://take.ms/onCop The `/build` folder is added to the `STATICFILES_DIRS` config, like this:
`
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/build"),
]
`

>And does it definitely happen before collectstatic is run?
Yup, Webpack is building the static files (js, css, img) before `collectstatic`. 

P.S.: I've solved the problem with this workaround: https://stackoverflow.com/a/51580328

**Comment by evansd** [comment]
> Sorry, but I don't understand what exactly do you want to see? I also can perform any debug tests you ask me to do

Well the nature of debugging is that you don't know what you're looking for until you see it. I would just have confirmed that the problem existed and then worked through step-by-step to see why the files were not being picked up. Trying to do that via instructions to someone else is much more difficult and time consuming.

> P.S.: I've solved the problem with this workaround: https://stackoverflow.com/a/51580328

Great! You didn't mention any "Missing staticfiles manifest entry" errors so I don't quite see how that workaround would be relevant, but anyway I'm glad it's solved the problem for you.
