### ISSUE TITLE
Provide mitigation for last-modified (mtime) of 0

### ISSUE THREAD

**Issue by twosigmajab** [evansd/whitenoise#222]
Currently, Whitenoise unconditionally adds a `Last-Modified` header to responses based on `file.stat.st_mtime`. It also uses the `mtime` to compute part of the `ETag` header.

This is a problem when serving static files from a filesystem beyond the user's control (e.g. some FUSE mount) that reports an `mtime` of 0. After Whitenoise sends the bogus `Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT` header **as well as the `ETag` header that, due to the always-0 mtime, is always the same for different versions of the same file that have the same file size** (which is common with SPA index.html files that come with frameworks like Angular and React), clients will send corresponding `If-Modified-Since` and `If-None-Match` headers in subsequent requests, and Whitenoise will send bogus `304 Not Modified` responses, resulting in clients using stale content from their local caches. I'm supporting many Whitenoise users who are experiencing this problem.

Would you accept a pull request that provided some mitigation for this?

For example:
1. Add a special-case check for `mtime == 0`. When found, don't trust it.
2. Provide an `ignore_mtime` option that mitigates filesystems that don't support `mtime`. If True, don't even waste time (or bytes transferred, etc.) computing and sending a `Last-Modified` header, and don't include the `mtime` in the `ETag` computation; instead use the file's inode number, as Apache does: https://httpd.apache.org/docs/2.4/mod/core.html#fileetag

**Comment by evansd** [comment]
Hi. Yes I'd definitely be open to changes which help fix this problem (it's amazing the unanticipated corner cases you get when your software is widely used!).

But it might be possible to work around this for now using the setting:
[WHITENOISE_ADD_HEADERS_FUNCTION](http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_ADD_HEADERS_FUNCTION)

If you set your own `Last-Modified` and `Etag` headers here then WhiteNoise won't overwrite them, although there's no way at present to stop it sending those headers altogether.

I think `ETag` is always used in preference to `Last-Modified` if it's present so it might work to just set `Last-Modified` to the current time and then set `ETag` by hashing the file. The hashing will make your application startup a bit slower, but it only gets done once.

**Comment by twosigmajab** [comment]
Thanks for the super helpful reply, @evansd! (Note: I've updated the description with more info.)

Here is the workaround I've provided to the Whitenoise users I'm supporting:
```python
import logging
from hashlib import md5
from io import DEFAULT_BUFFER_SIZE


log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())


def set_content_based_cache_headers(headers, path, url, hashimpl=md5):
    """Set ETag based on a digest of the requested file.

    Also, clear the Last-Modified header.

    Use with
    https://whitenoise.rtfd.io/en/stable/base.html#add_headers_function

    Whitenoise's default ETag algorithm only uses the file size and mtime.
    On ArtFS, mtime is always 0. In this case, two different versions of the
    same file that happen to have the same size get the same ETag, leading to
    clients using stale versions from cache. This is particularly likely with
    index.html files used with SPA frameworks, which contain little more than
    the inclusion of a JavaScript file, and where the only change between
    different versions may be a reference to index.a1b2c3.js changes to
    index.d4e5c6.js (i.e. no change in file size but possibly a completely
    different app).
    """
    hasher = hashimpl()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(DEFAULT_BUFFER_SIZE), b""):
            hasher.update(chunk)
    digest = hasher.hexdigest()
    etag = f"{hasher.name}-{digest}"
    headers["ETag"] = etag
    log.debug("path=%s url=%s : Set ETag=%s", path, url, etag)
    # Whitenoise favors If-None-Match when a request includes If-None-Match and
    # If-Modified-Since. The Flask dev server only supports HTTP/1.0, which
    # does not support ETags. Some clients (e.g. Firefox) send If-None-Match
    # anyway, but others (e.g. Chrome) do not, sending only If-Modified-Since.
    # So clear Last-Modified, otherwise Whitenoise will set it to 01 Jan 1970,
    # which, if Chrome sent as the only cache header to the Flask dev server,
    # would result in a bogus 304.
    headers["Last-Modified"] = ""  # Only way Whitenoise allows clearing.
```

Hope that helps others hitting this, and maybe even provides a reference for the fix!

Hope to get time to submit a fix to Whitenoise before too long, but not sure when I'll be able to. In the meantime, if you have any ideas on exactly what API and behavior changes you'd want to accept for this, please let me know. Or if you'd like to just get the fix in for this yourself, please don't wait for me.

Thanks again for all the help!

**Comment by evansd** [comment]
I think adding a special case check for mtimes of zero is probably a reasonable solution here. In which case we wouldn't sent `Last-Modified` or 'Etag` headers by default and it would up the user to provide something like your content-based etag implementation if they wanted caching.

I think that would be better than adding yet another configuration option.
