### ISSUE TITLE
Missing changelog for 4.1.3

### ISSUE THREAD

**Issue by bhrutledge** [evansd/whitenoise#229]
I'm looking into this report from [`safety check`](https://pypi.org/project/safety/):

```
╞══════════════════════════════════════════════════════════════════════════════╡
│ whitenoise                 │ 4.1.2     │ <4.1.3                   │ 37275    │
╞══════════════════════════════════════════════════════════════════════════════╡
│ whitenoise 4.1.3 change: Fix potential path traversal attack while running   │
│ in autorefresh mode on    Windows                                            │
╘══════════════════════════════════════════════════════════════════════════════╛
```

However, while there is a [4.1.3 release on PyPI](https://pypi.org/project/whitenoise/4.1.3/), I don't see a mention of it in the [changelog](http://whitenoise.evans.io/en/stable/changelog.html).

**Comment by evansd** [comment]
Oh, weird. I did update the [changelog](https://github.com/evansd/whitenoise/blob/master/docs/changelog.rst) but it looks like the docs didn't update. Maybe ReadTheDocs had a glitch at the time. I'll see if I can trigger a rebuild manually.

**Comment by evansd** [comment]
Rebuild fixed it
