### ISSUE TITLE
Missing staticfiles manifest entry for favicon.ico

### ISSUE THREAD

**Issue by jribbens** [evansd/whitenoise#239]
Django 2.1.14 with whitenoise 4.1.4 is throwing an exception in production `Missing staticfiles manifest entry for 'images/favicon.71317f9c63fb.ico'`.

The file `static/images/favicon.71317f9c63fb.ico` does exist (as does `static/images/favicon.ico`). `STATIC_ROOT` is set correctly.

`findstatic` from the command-line is perfectly happily finding both `favicon.ico` and `favicon.71317f9c63fb.ico`.

Changing  `STATICFILES_STORAGE` from `whitenoise.storage.CompressedManifestStaticFilesStorage` to `django.contrib.staticfiles.storage.StaticFilesStorage` makes the problem go away.

What could be causing this?

**Comment by evansd** [comment]
Thanks for reporting this. That's very odd. Can you try setting `STATICFILES_STORAGE` to `django.contrib.staticfiles.storage.ManifestStaticFilesStorage` and seeing if that gives the same problem?

**Comment by jribbens** [comment]
Aha! It did, which led to the discovery of the problem: someone had linked to the file using the hash explicitly. i.e. a template said `{% static "images/favicon.71317f9c63fb.ico" %}`. Sigh. Thanks for your help!

(I guess if anyone else has ever made such a peculiar mistake it might be worth adding a check for this and giving a specific helpful error message. But possibly nobody ever has...)
