### ISSUE TITLE
Content-Disposition header with inline disposition in Django 3.0 breaks in Safari

### ISSUE THREAD

**Issue by paltman** [evansd/whitenoise#240]
I can't determine if this is something that needs to be addressed in Whitenoise or in Django but in Django 3.0, a `Content-Disposition` header is being added as `inline` and that is causing Safari to not parse it.

This new header was added in [de4832c49b8a8cf00b2d602ab4d10c4ca69627bd](https://github.com/django/django/commit/de4832c49b8a8cf00b2d602ab4d10c4ca69627bd).

I can verify this works by adding this middleware before the WhiteNoiseMiddlware in my settings.py:

```python
def strip_content_disposition(get_response):
    def middleware(request):
        response = get_response(request)
        del response['Content-Disposition']
        return response
    return middleware
```

Obviously that's not a good solution for this, but I'm not sure what is or even if this is a Whitenoise issue or a Django issue.

**Comment by paltman** [comment]
Ended up using a setting built for this:

```python
def strip_content_disposition(headers, path, url):
    del headers["Content-Disposition"]


WHITENOISE_ADD_HEADERS_FUNCTION = strip_content_disposition
``` 

eliminates the need for the middleware.

Thanks for the suggestion, @jacobwegner

**Comment by peterflat** [comment]
Just a note that I am using Django 2.2 with whitenoise and this is an issue for Safari 13.  The
`WHITENOISE_ADD_HEADERS_FUNCTION ` Solution above works like a charm.

**Comment by evansd** [comment]
@peterflat That's very strange as the code which causes this problem wasn't added until Django 3.0 so probably you're hitting a different issue. In any case, you don't need the workaround if you use WhiteNoise v.5.0 or above.
