### ISSUE TITLE
Safari fails to load JavaScript due to "Invalid character" error when using Django 3.0

### ISSUE THREAD

**Issue by giilby** [evansd/whitenoise#241]
I'm not sure whether this is a Safari, Django 3, or WhiteNoise bug, and I suspect it's Safari, but I thought it wouldn't hurt to document here. After upgrading a simple app to Django 3 + WhiteNoise 4.1.4, the app stopped working in Safari because its JavaScript bundle failed to load. Downgrading to Django 2.2.8 fixed the issue, and when investigating differences between the two, I discovered that Django 3 changed the way that `Content-Disposition` is output for file responses: https://github.com/django/django/commit/de4832c49b8a8cf00b2d602ab4d10c4ca69627bd#diff-eeebc8cb56240caf13a9952431189fef. By either preventing `Content-Disposition` from being output for the JavaScript file, or by setting it to `inline` instead of `inline; filename="index.min.d9b11ca4d877.js.gz"`, Safari was able to load the script just fine. So, it appears that when `Content-Disposition: inline; filename="index.min.d9b11ca4d877.js.gz"` is set on the response for the JavaScript bundle, Safari fails to recognize that it's a gzip file and tries to parse it before decompressing.

I've created a demo of this issue: https://github.com/giilby/invalid-character-bug-demo. I'm happy to help resolve it in any way I can, and if we determine that it's actually a Django or Safari bug, I'll file a new report accordingly. Thanks for creating a great library, and thanks for your help!

My Safari version: 13.0.3 (15608.3.10.1.4)

**Comment by paltman** [comment]
See #240 - I closed it because I'm no longer blocked but it seems like there might should be something that does this by default so it works out of the box with Django 3.0.

**Comment by evansd** [comment]
Fixed in v5.0. Thanks for tracking down this issue and reporting it.
