### ISSUE TITLE
Django doesn't load new files from static directory until server restarted

### ISSUE THREAD

**Issue by arbazkiraak** [evansd/whitenoise#243]
I have a Django app in production which have the functionality to save the images to the `app/static/gallery/` directory from the app.

then application loads those images from the directory in the template.

```
<img src="{% static 'gallery/1.jpg' %}">
```

* Problem here is as the application is in production & constantly saves the images under `static/gallery` it won't load new images until I restarted the server.

I'm using `http://whitenoise.evans.io/en/stable/django.html#` to serve static files.

```
→ django-admin version
2.2.4
```

* How to tackle this problem to always serve static files to load them instantly without restarting the server.

**Comment by arbazkiraak** [comment]
### settings.py 


```
###! ENABLE THEM ON USE ONLY
# http://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support
if DEBUG is False:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240 # higher than the count of fields

if DEBUG is True:
    INSTALLED_APPS.insert(0,'whitenoise.runserver_nostatic')
```

**Comment by evansd** [comment]
Hi, I'm afraid WhiteNoise, and Django's static files system in general, aren't designed for this use case. Static files are meant to be those which are part of your application code base and don't change while the application is running (hence the name "static").

What you're looking for is what Django calls "media" files (not a great name). There's some documentation here on the Django site:
https://docs.djangoproject.com/en/3.0/topics/files/
