### ISSUE TITLE
Use whitenoise for tests

### ISSUE THREAD

**Issue by Pomax** [evansd/whitenoise#247]
I can't seem to find anything that explains how to make sure that whitenoise gets used during `manage test`, rather than the `django.contrib.staticfiles`. I have `whitenoise.runserver_nostatic` in my installed apps, above the contrib app, and `manag runserver` uses whitenoise as it should, but `manage test` shows it's not kicking in, and `manage test --nostatic` is an invalid runtime flag =(

Is there an easy/clean way to make Django use Whitenoise during test runs?

**Comment by dannluciano** [comment]
Hi I have the same question. My Selenium tests are broken after add ```STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' ```

**Comment by dannluciano** [comment]
@Pomax see this https://github.com/evansd/whitenoise/issues/204#issuecomment-439091496

**Comment by Pomax** [comment]
cheers
