### ISSUE TITLE
Add check to authorize requests domain for serving static files

### ISSUE THREAD

**Issue by thenewguy** [evansd/whitenoise#248]
It would be helpful to have a pluggable hook for telling whitenoise if the request domain is suitable for serving static files or not.  I.e. is the request actually actually on the static domain?  And return 404 or content based on true/false from the function

**Comment by evansd** [comment]
You should be able to do this easily enough by subclassing WhiteNoiseMiddleware e.g (untested code):
```py
from whitenoise.middleware import WhiteNoiseMiddleware 

class HostCheckingMiddleware(WhiteNoiseMiddleware):

    def __call__(self, request):
        # If the hostname doesn't match pass the request directly through to
        #  the next layer of middleware where it will result in a 404 response
        if request.headers["Host"] != "expected.host.name":
            return self.get_response(request)
        # Otherwise call the original whitenoise method
        return super().__call__(request)
```

If this turns out to be a widely used feature then I can consider adding direct support for it.

**Comment by thenewguy** [comment]
Will give that route a go and report back if I encounter any issues.  Thanks for the snippet

**Comment by adamchainz** [comment]
FYI separate static domains are no longer a “best practice”. HTTP/2 means it's better to serve your static assets from same domain, so they can be sent on the same connection as your HTML.
