### ISSUE TITLE
Serve html files without the .html extension?

### ISSUE THREAD

**Issue by scherrey** [evansd/whitenoise#249]
Newbie question here. Running whitenoise behind an extremely basic flask setup. Mostly want to operate this as a 99% static content site. I put my static *.html files under the static subdirectory but I'd like my links to not show the .html. What's the best practice method of doing this with whitenoise? 

FWIW - if there's a better option than flask I'm happy to switch. I'm not tied to anything here. Just want to make a nice flexible mostly static website.

**Comment by evansd** [comment]
Hi, yes you can use the [index_file](http://whitenoise.evans.io/en/stable/base.html#index-files) option for this.
