### ISSUE TITLE
When DEBUG=True DjangoWhiteNoise does not look at AppDirectories for static files

### ISSUE THREAD

**Issue by pykler** [evansd/whitenoise#25]
When DEBUG=True DjangoWhiteNoise does not look at AppDirectories for static files

**Comment by evansd** [comment]
In case anyone stumbles across this issue in future, WhiteNoise v2.0 now supports serving files from AppDirectories by default when DEBUG=True.

**Comment by akramnarejo** [comment]
> In case anyone stumbles across this issue in future, WhiteNoise v2.0 now supports serving files from AppDirectories by default when DEBUG=True.

what if debug=False that's my issue facing now.
