### ISSUE TITLE
Add a config to change set manifest_strict in settings

### ISSUE THREAD

**Issue by MegacoderKim** [evansd/whitenoise#252]
Since  `whitenoise.storage.CompressedManifestStaticFilesStorage` already inherits from from django `django.contrib.staticfiles.storage.ManifestStaticFilesStorage` can we make  `ManifestStaticFilesStorage.manifest_strict` configurable to `False` via a config? 
I'd be happy to add this.

**Comment by evansd** [comment]
Yeah, that sounds look a good idea. Thanks!
