### ISSUE TITLE
Consider splitting Django middleware/integration into its own package?

### ISSUE THREAD

**Issue by Conan-Kudo** [evansd/whitenoise#255]
I've started looking at using WhiteNoise with a few Flask apps I work on, but one thing that makes me a bit confused is whether or not having Django installed is needed. It _seems_ like it's not required for the basic functionality, but a lot of the code has Django imports.

Would you please consider splitting the Django dependent code out into its own PyPI package (i.e. `Django-WhiteNoise` Python package for Django users)? It would make it easier for me to avoid accidentally requiring Django for my Flask applications.

**Comment by WhyNotHugo** [comment]
Probably makes more sense to make `django` an optional extra dependency.  
This'll avoid installing it in case you don't need it, but keep things simple for everyone else.

**Comment by Conan-Kudo** [comment]
Well, the problem is that it's unclear which parts of the code would trigger an `import django` scenario. Already Django is not required by the setuptools metadata.

**Comment by evansd** [comment]
The only modules which import Django are ones which you could only use with Django anyway, i..e the Django middleware, the storage backend and the runserver command wrapper. As confirmed with grep:
```sh
dave@carnap:~/projects/whitenoise/whitenoise$ grep -r import --include='*.py' | grep django
middleware.py:from django.conf import settings
middleware.py:from django.contrib.staticfiles.storage import staticfiles_storage
middleware.py:from django.contrib.staticfiles import finders
middleware.py:from django.http import FileResponse
middleware.py:from django.urls import get_script_prefix
storage.py:from django.conf import settings
storage.py:from django.contrib.staticfiles.storage import (
runserver_nostatic/management/commands/runserver.py:from django.apps import apps
```

Everything else is pure WSGI and has no external dependencies.

I'm not going to split the package as that will create extra management overhead for me, but I'd be happy to add some kind of clarification to the docs.

Incidentally, I don't understand the worry about accidentally importing Django. Presumably you don't have Django installed in the environment of your Flask apps. So if you run it and it doesn't blow up with an import error then you know it hasn't tried to import Django, don't you?
