### ISSUE TITLE
ValueError at / Missing staticfiles manifest entry for 'images\favicon.ico'

### ISSUE THREAD

**Issue by galactic0** [evansd/whitenoise#256]
its leading to internal server error 500

settings.py 

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
'static'
]

Internal Server Error: /

ValueError at /
Missing staticfiles manifest entry for 'images\favicon.ico'

Request Method: GET
Request URL: http://127.0.0.1:8000/
Django Version: 2.0.4
Python Executable: D:\Amtpl project by aman\AMTPL - Copy\env\Scripts\python.exe
Python Version: 3.8.0

**Comment by evansd** [comment]
It looks like you're using a Windows backslash in the URL, rather than a forward slash. It should be `images/favicon.co`

**Comment by galactic0** [comment]
thanks a ton evan,
 I cont seem to find where i have referenced this asset, neither in my
templates or my project.
would be great if you could point me in the right direction.

Thanks in advance.

**Comment by evansd** [comment]
Sorry, if your code was public on github I could probably find it for you, but without that I can't really help.

**Comment by galactic0** [comment]
nternal Server Error: /

ValueError at /
The file 'assets\css\fontawesome-all.min.css' could not be found with
<whitenoise.storage.CompressedManifestStaticFilesStorage object at
0x7f8c056fe780>.

Request Method: GET
Request URL: https://areon-mobility.herokuapp.com/
Django Version: 2.0.4
Python Executable: /app/.heroku/python/bin/python
Python Version: 3.6.10
Python Path: ['/app', '/app/.heroku/python/bin', '/app',
'/app/.heroku/python/lib/python36.zip',
'/app/.heroku/python/lib/python3.6',
'/app/.heroku/python/lib/python3.6/lib-dynload',
'/app/.heroku/python/lib/python3.6/site-packages']
Server time: Wed, 3 Jun 2020 13:16:08 +0000
Exception Value: The file 'assets\css\fontawesome-all.min.css' could not be
found with <whitenoise.storage.CompressedManifestStaticFilesStorage object
at 0x7f8c056fe780>.
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
csrftoken =
'PRM0XTgGYM40e4ioaL2kSMoLwC6WndzkkMFCuQxlAjTuaaRh5WPn4D8cH2uOridZ'

META:
CSRF_COOKIE =
'PRM0XTgGYM40e4ioaL2kSMoLwC6WndzkkMFCuQxlAjTuaaRh5WPn4D8cH2uOridZ'
HTTP_ACCEPT =
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'en-GB,en;q=0.9,en-US;q=0.8,hi;q=0.7'
HTTP_CACHE_CONTROL = 'no-cache'
HTTP_CONNECTION = 'close'
HTTP_CONNECT_TIME = '1'
HTTP_COOKIE =
'csrftoken=PRM0XTgGYM40e4ioaL2kSMoLwC6WndzkkMFCuQxlAjTuaaRh5WPn4D8cH2uOridZ'
HTTP_HOST = 'areon-mobility.herokuapp.com'
HTTP_PRAGMA = 'no-cache'
HTTP_SEC_FETCH_DEST = 'document'
HTTP_SEC_FETCH_MODE = 'navigate'
HTTP_SEC_FETCH_SITE = 'none'
HTTP_SEC_FETCH_USER = '?1'
HTTP_TOTAL_ROUTE_TIME = '5004'
HTTP_UPGRADE_INSECURE_REQUESTS = '1'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36'
HTTP_VIA = '1.1 vegur'
HTTP_X_FORWARDED_FOR = '106.212.151.155'
HTTP_X_FORWARDED_PORT = '443'
HTTP_X_FORWARDED_PROTO = 'https'
HTTP_X_REQUEST_ID = 'c848f41f-3255-434a-b964-8e99c1abf469'
HTTP_X_REQUEST_START = '1591190160440'
PATH_INFO = '/'
QUERY_STRING = ''
RAW_URI = '/'
REMOTE_ADDR = '10.38.205.57'
REMOTE_PORT = '18346'
REQUEST_METHOD = 'GET'
SCRIPT_NAME = ''
SERVER_NAME = '0.0.0.0'
SERVER_PORT = '11301'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SOFTWARE = 'gunicorn/20.0.4'
gunicorn.socket = <socket.socket fd=9, family=AddressFamily.AF_INET,
type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.16.241.102', 11301),
raddr=('10.38.205.57', 18346)>
wsgi.errors = <gunicorn.http.wsgi.WSGIErrorsWrapper object at
0x7f8c05598470>
wsgi.file_wrapper = ''
wsgi.input = <gunicorn.http.body.Body object at 0x7f8c05598438>

root@localhost
6:46 PM (28 minutes ago)
[image: image.gif]
[image: image.gif]
to me
[image: image.gif]
Internal Server Error: /

ValueError at /
The file 'assets\css\fontawesome-all.min.css' could not be found with
<whitenoise.storage.CompressedManifestStaticFilesStorage object at
0x7f8c056fe780>.

Request Method: GET
Request URL: https://areon-mobility.herokuapp.com/
Django Version: 2.0.4
Python Executable: /app/.heroku/python/bin/python
Python Version: 3.6.10
Python Path: ['/app', '/app/.heroku/python/bin', '/app',
'/app/.heroku/python/lib/python36.zip',
'/app/.heroku/python/lib/python3.6',
'/app/.heroku/python/lib/python3.6/lib-dynload',
'/app/.heroku/python/lib/python3.6/site-packages']
Server time: Wed, 3 Jun 2020 13:16:13 +0000
HTTP_ACCEPT = '*/*'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'en-GB,en;q=0.9,en-US;q=0.8,hi;q=0.7'
HTTP_CONNECTION = 'close'
HTTP_CONNECT_TIME = '1'
HTTP_COOKIE =
'csrftoken=PRM0XTgGYM40e4ioaL2kSMoLwC6WndzkkMFCuQxlAjTuaaRh5WPn4D8cH2uOridZ'
HTTP_HOST = 'areon-mobility.herokuapp.com'
HTTP_SEC_FETCH_DEST = 'empty'
HTTP_SEC_FETCH_MODE = 'cors'
HTTP_SEC_FETCH_SITE = 'none'
HTTP_TOTAL_ROUTE_TIME = '0'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36'
HTTP_VIA = '1.1 vegur'
HTTP_X_FORWARDED_FOR = '106.212.151.155'
HTTP_X_FORWARDED_PORT = '443'
HTTP_X_FORWARDED_PROTO = 'https'
HTTP_X_REQUEST_ID = 'c868d735-49ce-416e-96bf-4ae4e466de8c'
HTTP_X_REQUEST_START = '1591190173587'
PATH_INFO = '/'
QUERY_STRING = ''
RAW_URI = '/'
REMOTE_ADDR = '10.38.205.57'
REMOTE_PORT = '15594'
REQUEST_METHOD = 'GET'
SCRIPT_NAME = ''
SERVER_NAME = '0.0.0.0'
SERVER_PORT = '11301'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SOFTWARE = 'gunicorn/20.0.4'
gunicorn.socket = <socket.socket fd=9, family=AddressFamily.AF_INET,
type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.16.241.102', 11301),
raddr=('10.38.205.57', 15594)>
wsgi.errors = <gunicorn.http.wsgi.WSGIErrorsWrapper object at
0x7f8c0513e898>
wsgi.file_wrapper = ''
wsgi.input = <gunicorn.http.body.Body object at 0x7f8c0513e860>

**Comment by galactic0** [comment]
the above error said that the files are missing in staticfiles i have just
checked through heroku bash command the files are preset but still the
error persists

**Comment by evansd** [comment]
Again, looks like you're using back slashes instead of forward slashes. You should have `assets/css/fontawesome-all.min.css` instead of `assets\css\fontawesome-all.min.css`

**Comment by galactic0** [comment]
its working fine now  https://areon-mobility.herokuapp.com/, thanks a ton
dave, this '\' working working fine on local machine so i didnt notice the
issue.
Anyways, how can i follow you on twitter or any blog if you have, i have
just started my journey of web dev's.

Regards,
