### ISSUE TITLE
Bootstrap 4.4.1 nav bar hamburger menu in mobile views disappeared in 5.2.0 update

### ISSUE THREAD

**Issue by aschulak** [evansd/whitenoise#272]
When I updated from 5.1 to 5.2.0 my Bootstrap 4.4.1 nav bar hamburger menu icon in mobile views disappeared. Reverting back to 5.1 fixed this issue. 

Bootstrap code is pretty boilerplate from here: https://getbootstrap.com/docs/4.0/components/navbar/

Icon css is: 
`.navbar-toggler-icon {
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255,255,255, 1)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");
}

Wondering if I need to update something on my end or if this is an issue.

Thanks,
A

**Comment by adamchainz** [comment]
I don't see how your issue has anything to do with Whitenoise. If you can provide an example how this is related to Whitenoise, I can take a look.
