### ISSUE TITLE
Server Error 500 - Debug = False

### ISSUE THREAD

**Issue by Kronholt** [evansd/whitenoise#274]
I am trying to use whitenoise to serve my static files for a django project. 

I receive a Server Error (500) 
When debug = False 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

When I run the program with 
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
the static files are served correctly.

**Comment by muhammadaamir123** [comment]
> I am trying to use whitenoise to serve my static files for a django project.
> 
> I receive a Server Error (500)
> When debug = False
> STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
> 
> When I run the program with
> STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
> the static files are served correctly.

Do you find any solve about this issue? Please share it with me. I'm also facing same issue.

**Comment by merwok** [comment]
You need to give more info to get help.  What are the whitenoise options?  Do you get any error details in the 500 response, or in the terminal where you run the django server?  Can you enable DEBUG and get a 500 with more details?

**Comment by muhammadaamir123** [comment]
I make it solve by replacing this: 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
To this:
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

**Comment by merwok** [comment]
But then you’re not using whitenoise, so that gives no useful information to understand the problem 😐

**Comment by evansd** [comment]
You don't need to use the Whitenoise storage backend to use Whitenoise. It's only needed if you want to pre-compress your files. But if switching storage backends makes the problem go away then it suggests something is going wrong when running `collectstatic`. I'd try running
```sh
python manage.py collectstatic
```
And see if that gives you useful errors.

**Comment by AlanBourkePgi** [comment]
I've just been fighting this for a day. In my case the issue was my base Django template having a commented-out reference to a Bootstrap css file that was there from during the local development process. It seems Whitenoise will still try to process the reference despite it being commented out. Once I removed it completely everything worked.

**Comment by adamchainz** [comment]
There's no clear bug report in this issue, and several have been discussed. I'm going to close the issue now. If you have any particular problems please open a new report with as much information as possible.

**Comment by pfcodes** [comment]
I'm having this same issue. The weird thing is it open happens in production with `Debug = False`

**Comment by merwok** [comment]
See the previous comment: this ticket does not clearly discuss one issue, and your comment also does not give any required details.

**Comment by pfcodes** [comment]
To anyone who reaches this page in the future. The solution for me was to use `whitenoise.storage.CompressedStaticFilesStorage` in the remote environment with `DEBUG` set to `False`


Found the answer here: https://stackoverflow.com/a/56259827/8877418
