### ISSUE TITLE
Example with Bottle?

### ISSUE THREAD

**Issue by AlecTaylor** [evansd/whitenoise#28]
I am using [bottle](http://bottlepy.org) on Heroku. Heroku recommends your project for static file serving from a Python app.

Looking at your WSGI example, I am unsure how well it can be integrated. I am using [gunicorn](http://gunicorn.org) as my server.

**Comment by evansd** [comment]
I haven't used Bottle myself, but WhiteNoise ought to work with fine with it. From a quick glance at the Bottle [WSGI documentation](http://bottlepy.org/docs/dev/deployment.html#switching-the-server-backend) I think you'll need to create a `my_wsgi_app.py` file like this:
```python
import bottle
from whitenoise import WhiteNoise

# import your Bottle app here

application = bottle.default_app()
application = WhiteNoise(application, root='/path/to/static/files')
```

You'd then run this under gunicorn with something like this:
`gunicorn my_wsgi_app`

Hopefully that's enough to get you started.

**Comment by AlecTaylor** [comment]
Thanks @evansd, just tried that, but got this error:
```
gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
```

Here is my code:
```
from sys import platform

from bottle import Bottle, response, static_file
from whitenoise import WhiteNoise

static_app = Bottle(catchall=False, autojson=True)


@static_app.hook('after_request')
def enable_cors():
    response.headers['Access-Control-Allow-Origin'] = '*'  # Take out '*' in production!

@static_app.route('/foo')
def root():  # Useful for testing, as in production I will merge a bunch of Bottle apps together
    response.status = 404
    return {'error': 'NotFound', 'error_message': 'Nothing on this route'}


static_app = WhiteNoise(static_app, root='/static/web-frontend-master/www')

'''
if __name__ == '__main__':
    static_app.run(server='wsgiref' if platform == 'win32' else 'gunicorn',
                   host='0.0.0.0', port=int(environ.get('PORT', 5555)), debug=True)
'''
```

**Comment by evansd** [comment]
Hi @AlecTaylor,

I don't know enough about Bottle to give much advice, but WhiteNoise is just wsgi middleware so whatever pattern is normally used for plugging middleware into Bottle apps ought to work.

I found this page here which gave an example: http://bottlepy.org/docs/dev/recipes.html

Just looking at your code I can see one issue though, which is that you're calling a `run` method on `static_app`. By this point in the code `static_app` is a WhiteNoise wsgi instance and so won't have a run method. From the linked example, I think you need to call `bottle.run(app=static_app, ...)`

Sorry I can't be more help. You might be better off asking for help from the Bottle community. Just explain that WhiteNoise is wsgi middleware and that should be all they need to know.
