### ISSUE TITLE
Non-post-processed files

### ISSUE THREAD

**Issue by cajoek** [evansd/whitenoise#288]
Hi, I'm a little confused about the post processing (gzip compression in my case).
The original files are still in the STATIC_ROOT directory, are they needed or are only the compressed files needed for deployment?
If the original files are not needed how do I remove/separate them?

Thanks!

**Comment by LucidDan** [comment]
Hi! Yes, I'm pretty sure you still need them. The original files would be used in the event that a request is made for an uncompressed asset, e.g. if a client doesn't accept any of the available compression encodings. 
Whitenoise just serves up the assets as-is once they've been collected and processed; e.g. it won't automatically decompress a file to serve it to a client that doesn't accept a compression encoding.

**Comment by adamchainz** [comment]
Also, if you are referring to unhashed files, you can normally safely remove them with [`WHITENOISE_KEEP_ONLY_HASHED_FILES = True`](https://whitenoise.evans.io/en/stable/django.html#WHITENOISE_KEEP_ONLY_HASHED_FILES).
