### ISSUE TITLE
CompressedManifestStaticFilesStorage not fully respecting WHITENOISE_MANIFEST_STRICT=False

### ISSUE THREAD

**Issue by sergioisidoro** [evansd/whitenoise#289]
With the following configuration:
```
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
```

I'm getting an **expected** error, since the `images/abstract-graphic.svg` is indeed missing from static files
```
ValueError: Missing staticfiles manifest entry for 'images/abstract-graphic.svg'
```

According to the docs - http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_MANIFEST_STRICT -  i need to disable Manifest strict setting. Adding `WHITENOISE_MANIFEST_STRICT = False` I would expect this error to subside, but instead I get 
```
ValueError: The file 'images/abstract-graphic.svg' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0xffff8ffcde20>.
```

The trace comes from:
```
|   File "/usr/local/lib/python3.9/site-packages/whitenoise/storage.py", line 166, in hashed_name
|     name = super(CompressedManifestStaticFilesStorage, self).hashed_name(
|   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 88, in hashed_name
|     raise ValueError("The file '%s' could not be found with %r." % (filename, self))
```

Changing the storage to `STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"` works as expected, with all errors being silenced. 

From what I read in the documentation I would expect the same to happen with `WHITENOISE_MANIFEST_STRICT=False`.

Wondering if related to this change that happened recently-ish: https://github.com/evansd/whitenoise/commit/15c9ee79fe9ce40f1df66624e499f46ece4b73d8

**Comment by LucidDan** [comment]
Setting WHITENOISE_MANIFEST_STRICT to False will stop it from raising a ValueError if the file does not have an entry in the manifest (which was that first ValueError you posted), but it'll still fail if the file doesn't exist or has no permissions to access, which looks like the problem you're hitting in the second ValueError.

With CompressedStaticFilesStorage, it'll just fail to find the file, and potentially return a 404.

I think the Whitenoise documentation is actually slightly wrong (or at least, misleading) here...and the Django documentation saying "nonexistent paths will remain unchanged" could be stated more clearly, too.
