### ISSUE TITLE
error when run command python manage.py collectstatic

### ISSUE THREAD

**Issue by saaz181** [evansd/whitenoise#291]
when u hit the python manage.py collectstatic for some reason it show this error:
whitenoise.storage.MissingFileError: The file 'admin/jquery.ui.datepicker.jalali/themes/base/images/ui-bg_glass_55_fbf9ee_1x400.png' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x00000256B631F610>.

The CSS file 'admin\jquery.ui.datepicker.jalali\themes\base\jquery-ui.min.css' references a file which could not be found:
  admin/jquery.ui.datepicker.jalali/themes/base/images/ui-bg_glass_55_fbf9ee_1x400.png 

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.

I am using python 3.9 and Django 3.2.6

NOTE:
but it works even after this error as far as I tested the app but it can bugs somewhere in app

**Comment by evansd** [comment]
Hi, sorry, this is more a question for https://stackoverflow.com/ than a bug in the library.
