### ISSUE TITLE
whitenoise doesn't respect changing `X-Script-Name`

### ISSUE THREAD

**Issue by jamt9000** [evansd/whitenoise#293]
When using `X-Script-Name` to change the `SCRIPT_NAME` for a request, the value used for the first request received is then used for all subsequent requests, meaning that static content with `{% static 'style.css' %}` has the wrong URL whereas links using `{% url 'home' %}` have the correct URL.

```
curl -s -H 'X-Script-Name: /asdf' localhost:8888/portal/ | grep asdf
<link rel="stylesheet" href="/asdf/static/style.css">
<a href="/asdf/portal/home">home</a>


curl -s -H 'X-Script-Name: /asdf2' localhost:8888/portal/ | grep asdf
<link rel="stylesheet" href="/asdf/static/style.css">
<a href="/asdf2/portal/home">home</a>
```

For the first the WSGI environ is

`{'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fca25070eb0>, 'wsgi.version': (1, 0), 'wsgi.multithread': False, 'wsgi.multiprocess': False, 'wsgi.run_once': False, 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>, 'wsgi.input_terminated': True, 'SERVER_SOFTWARE': 'gunicorn/20.1.0', 'wsgi.input': <gunicorn.http.body.Body object at 0x7fca24fcb160>, 'gunicorn.socket': <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.23.0.3', 8000), raddr=('172.23.0.1', 61760)>, 'REQUEST_METHOD': 'GET', 'QUERY_STRING': '', 'RAW_URI': '/portal/login/', 'SERVER_PROTOCOL': 'HTTP/1.1', 'HTTP_HOST': 'localhost:8888', 'HTTP_USER_AGENT': 'curl/7.77.0', 'HTTP_ACCEPT': '*/*', 'HTTP_X_SCRIPT_NAME': '/asdf', 'wsgi.url_scheme': 'http', 'REMOTE_ADDR': '172.23.0.1', 'REMOTE_PORT': '61760', 'SERVER_NAME': '0.0.0.0', 'SERVER_PORT': '8000', 'PATH_INFO': '/portal/login/', 'SCRIPT_NAME': '/asdf'}`

For the second it is 

`{'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fca25070eb0>, 'wsgi.version': (1, 0), 'wsgi.multithread': False, 'wsgi.multiprocess': False, 'wsgi.run_once': False, 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>, 'wsgi.input_terminated': True, 'SERVER_SOFTWARE': 'gunicorn/20.1.0', 'wsgi.input': <gunicorn.http.body.Body object at 0x7fca24fcb160>, 'gunicorn.socket': <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.23.0.3', 8000), raddr=('172.23.0.1', 61760)>, 'REQUEST_METHOD': 'GET', 'QUERY_STRING': '', 'RAW_URI': '/portal/login/', 'SERVER_PROTOCOL': 'HTTP/1.1', 'HTTP_HOST': 'localhost:8888', 'HTTP_USER_AGENT': 'curl/7.77.0', 'HTTP_ACCEPT': '*/*', 'HTTP_X_SCRIPT_NAME': '/asdf2', 'wsgi.url_scheme': 'http', 'REMOTE_ADDR': '172.23.0.1', 'REMOTE_PORT': '61760', 'SERVER_NAME': '0.0.0.0', 'SERVER_PORT': '8000', 'PATH_INFO': '/portal/login/', 'SCRIPT_NAME': '/asdf2'}`

So it seems whitenoise isn't respecting the changed `environ["SCRIPT_NAME"]`

Maybe related: #140

**Comment by evansd** [comment]
Whitenoise isn't involved in generating the URLs: `{% static 'style.css' %}` just uses the default Django template tag.

Probably the behaviour you're seeing is due to the fact that Django `get_static_prefix()` function caches the script prefix value. There's a `clear_script_prefix()` function which might do what you want if you call it from the right place in your request handling sequence:
https://github.com/django/django/blob/dfdf1c68645627f54259dbe25f5b42329ee83b5d/django/urls/base.py#L107-L123

In any case, this isn't specifically a Whitenoise bug so I'm going to close it.

**Comment by jamt9000** [comment]
Thanks for the pointers...seems there are lots of pitfalls getting django to work under a subpath.

I'm now trying clearing the prefix, but unfortunately that doesn't work.

Even though printing the the prefix in the view shows the right value, it still is wrong in the template.

```
def home(request):
    from django.urls import base
    print("PREFIX IS", base._prefixes.value)
    return render(request, "portal/home.html", {})
```

```
curl -s -H 'X-Script-Name: /asdf' localhost:8888/portal/home | grep static
    <link rel="stylesheet" href="/asdf/static/style.css">

curl -s -H 'X-Script-Name: /asdf2' localhost:8888/portal/home | grep static
<link rel="stylesheet" href="/asdf/static/style.css">
```

Output

```
PREFIX IS /asdf/
PREFIX IS /asdf2/
```
