### ISSUE TITLE
Missing or "*" Accept-Encoding unhandled

### ISSUE THREAD

**Issue by rtibbles** [evansd/whitenoise#303]
According to the [MDN description of Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) and backed up by the [official spec](https://httpwg.org/specs/rfc7231.html#header.accept-encoding), the lack of an `Accept-Encoding` header or a value of `"*"` means that any encoding can be served.

I think this could be handled by updating the `get_path_and_headers` method of the `StaticFile` class to:

```
    def get_path_and_headers(self, request_headers):
        accept_encoding = request_headers.get("HTTP_ACCEPT_ENCODING", "*")
        # These are sorted by size so first match is the best
        for encoding_re, path, headers in self.alternatives:
            if accept_encoding == "*" or encoding_re.search(accept_encoding):
                return path, headers
```

**Comment by adamchainz** [comment]
This seems reasonable. Do you know what clients it would affect? Would you be willing to prepare a PR, with tests?

**Comment by rtibbles** [comment]
I am not sure it actually affects any real world clients - I can't seem to quickly uncover any listing of common `Accept-Encoding` headers for different clients, so this may be an entirely theoretical problem.

Happy to have a go at a fix and tests!
