### ISSUE TITLE
UWSGI and Whitenoise

### ISSUE THREAD

**Issue by chiel1980** [evansd/whitenoise#31]
Hello,

I am running 2 docker containers: 1) nginx proxy and 2) uwsgi with my django 1.8 app.
I have to solve the static files issue since nginx normally handles the static files so I found whitenoise.
I followed the simple howto and changed my wsgi.py:
```
import os

from django.core.wsgi import get_wsgi_application
from whitenoise.django import DjangoWhiteNoise

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ironman.settings")
#os.environ("DJANGO_SETTINGS_MODULE", "ironman.settings")

application = get_wsgi_application()
application = DjangoWhiteNoise(application)
```

and my settings.py:

```
WSGI_APPLICATION = 'ironman.wsgi.application'
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
```
And I loaded the staticcontent app:

```
    'django.contrib.staticfiles',
```

The error I am getting from UWSGI:

```
Traceback (most recent call last):
  File "./ironman/wsgi.py", line 13, in <module>
    from whitenoise.django import DjangoWhiteNoise
  File "/usr/local/lib/python2.7/dist-packages/whitenoise/django.py", line 14, in <module>
    from django.contrib.staticfiles.storage import staticfiles_storage
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/storage.py", line 12, in <module>
    from django.core.cache import (
  File "/usr/local/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTING
S_MODULE or call settings.configure() before accessing settings.
```

I've tried setting the CACHES and DEFAULT_CACHE_ALIAS  in my settings.py but to no effect.

What am I doing wrong?

Thanks for all the help.

Michiel

**Comment by evansd** [comment]
I think the problem here is that you need the line:

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ironman.settings")

to come at the top of the `wsgi.py` file, before you import `DjangoWhiteNoise`.

**Comment by chiel1980** [comment]
Yes that's it! :)
:+1:

**Comment by reverie** [comment]
Just wasted a few hours on this. It should be considered a bug & fixed in whitenoise.

**Comment by evansd** [comment]
Yeah, this is frustrating but the bug is in Django not in WhiteNoise. I've filed a ticket about it (https://code.djangoproject.com/ticket/25034) so hopefully this won't be a problem in future versions of Django.

For now, I've added some code into WhiteNoise which tries to catch this error and provide a more helpful error message which explains what the actual problem is.

**Comment by reverie** [comment]
Oh I see. That sounds good. Sorry for blaming wn. :)
