### ISSUE TITLE
Serving media files

### ISSUE THREAD

**Issue by moonstruck** [evansd/whitenoise#32]
Is there any option in DjangoWhiteNoise to serve media files like MediaCling of dj-static?

**Comment by evansd** [comment]
I'm afraid not. WhiteNoise is optimized to serve a small set of files that remain fixed while the application is running, and it wouldn't work well for this purpose. I think most people using WhiteNoise use Amazon S3 to store and serve their media files.

If you just want to serve media files in development then I've used a pattern like this in my `urls.py` file:
```python
if settings.SERVE_MEDIA_FILES:
    urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),)
```

And then in development I have `SERVE_MEDIA_FILES = True`.

**Comment by vstoykov** [comment]
Actually WhiteNoise can be used to serve media files. Probably it's not optimal but still if you use some sort of CDN you can put in your wsgi.py file the following code:

    from django.conf import settings
    from whitenoise import WhiteNoise
    from whitenoise.django import DjangoWhiteNoise

    application = WhiteNoise(
        DjangoWhiteNoise(get_wsgi_application()),
        root=settings.MEDIA_ROOT,
        prefix='/media/',
    )

Prefix is hardcoded because if you use CDN you can can configure your `MEDIA_URL` to be absolute URL of the CDN.

**Comment by evansd** [comment]
@vstoykov I'm afraid this won't work how you expect it to. WhiteNoise scans for available files on startup and assumes that they won't change for the lifetime of the process. So any new files that get uploaded while the app is running won't get served.
