### ISSUE TITLE
Drop Django 3.0/3.1 versions

### ISSUE THREAD

**Issue by pauloxnet** [evansd/whitenoise#335]
Django versions 3.0 and 3.1 are not maintained anymore, I propose to remove them before the next release of whitenoise.

**Comment by adamchainz** [comment]
I maintain support for intermediate versions between LTS versions, until the LTS is dropped. This is because Django recommends upgrading between intermediate versions, and it's normally not much overhead. So in the future I'll drop 2.2, 3.0, and 3.1 at the same time.

**Comment by pauloxnet** [comment]
Thanks for the clarification.
