### ISSUE TITLE
DEBUG=False not working due to Suffixes

### ISSUE THREAD

**Issue by cancan101** [evansd/whitenoise#35]
When using whitenoise in `DEBUG=True`, templates request files like:
`/static/rest_framework/css/bootstrap-tweaks.css`
which are properly served up.

With  `DEBUG=False` the template requests:
`/static/rest_framework/css/bootstrap-tweaks.964c59eecf05.css` and this file is not properly served.

What is causing this suffix to be inserted?

When I am running with `DEBUG=False` , If I manually navigate to `/static/rest_framework/css/bootstrap-tweaks.css`, the content is served.

**Comment by evansd** [comment]
The suffix is inserted by Django's staticfiles storage system: https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#manifeststaticfilesstorage

It means each version of the file gets a unique name so the files can be safely cached forever.

It sounds like you might not have run `python manage.py collectstatic` first (see http://whitenoise.evans.io/en/latest/django.html#make-sure-staticfiles-is-configured-correctly)

**Comment by cancan101** [comment]
I have run `python manage.py collectstatic` and I see: `78 static files copied to...`

**Comment by evansd** [comment]
Hmm... Sounds like you did the right thing. Can you post the contents of your `STATIC_ROOT` directory? And maybe the relevant bit of your `settings.py` if that's OK.

**Comment by cancan101** [comment]
It looks like Docker, et al. is messing with `STATIC_ROOT = os.path.join(BASE_DIR, ...)`.

**Comment by cancan101** [comment]
Okay. Reopening. Still not sure:
```
$ls -l  /usr/src/app/static/
total 12
drwxr-xr-x 5 root root 4096 Jul  1 20:12 admin
drwxr-xr-x 3 root root 4096 Jul  1 20:12 gis
drwxr-xr-x 6 root root 4096 Jul  1 20:12 rest_framework
```

```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
print "STATIC_ROOT=%s" % STATIC_ROOT
```

```
STATIC_ROOT=/usr/src/app/static/
```

**Comment by evansd** [comment]
Can you use `ls -R` so I can see the files in the subdirectories?

**Comment by cancan101** [comment]
```
/usr/src/app/static/rest_framework/css:
total 120
-rw-r--r-- 1 root root   3143 Jul  1 20:12 bootstrap-tweaks.css
-rw-r--r-- 1 root root 109518 Jul  1 20:12 bootstrap.min.css
-rw-r--r-- 1 root root    944 Jul  1 20:12 default.css
-rw-r--r-- 1 root root    817 Jul  1 20:12 prettify.css
```

**Comment by evansd** [comment]
That's bizarre. I don't understand how you're getting versioned filenames from `{% static ... %}` but they're not being generated by `collectstatic`. What's `STATICFILES_STORAGE` set to? And at what point during the build process are you running `collectstatic`?

**Comment by cancan101** [comment]
Okay. The issue is that when I ran collectstatic, I did not have `STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'` set.

**Comment by evansd** [comment]
Ah! Glad there was a simple explanation.
