### ISSUE TITLE
2.0 broke STATIC_URL handling in Django for absolute URLs

### ISSUE THREAD

**Issue by dominicrodger** [evansd/whitenoise#36]
Firstly, thanks for Whitenoise, I've really appreciated it.

I've bumped into a small problem with Whitenoise 2.0. I have the following as my ``STATIC_URL``:

    STATIC_URL = 'https://static.example.com/'

This makes whitenoise fail to load correctly, since get_prefix_url returns ``'/'``, and so you get the odd error (from [here](https://github.com/evansd/whitenoise/blob/39de5e09270b85c43ce994a90c5e8a2e1e284a10/whitenoise/django.py#L70)):

> Both STATIC_URL and STATIC_ROOT settings must be configured to use DjangoWhiteNoise

Reverting to ``whitenoise==1.0.6`` works. I think the breaking change is 25f5757b41f5d876252dff873ecb88b177793a3e.

I'm not quite sure what the breaking change was intending to do, so I'm not quite sure what an appropriate patch would be. I think it's something to do with local development based on [the release notes of 2.0](https://github.com/evansd/whitenoise/blob/master/CHANGELOG.rst#v20).

**Comment by evansd** [comment]
Thanks for reporting this.

I think actually it was a bug in 1.0.6 that it _didn't_ throw an error in this case. The problem is that WhiteNoise has to strip the domain part from `STATIC_URL` to determine the prefix under which to serve your static files and in your case the prefix is empty. This means your static files get served from the root of your domain where they can potentially clash with your application URLs. In practice you can probably get away with this most of the time, but it's not a good idea (it's effectively like setting `STATIC_URL` to '/' which Django won't let you do).

The best thing would be to set `STATIC_URL` to something like `https://static.example.com/static/` and then everything should work fine.

As you rightly point out though, the error message is pretty unhelpful so I'll look at improving that.

**Comment by dominicrodger** [comment]
Thanks for taking a look @evansd :)

I'm confused though - I thought it was fairly standard to have a separate (bare) domain as ``STATIC_URL``. If Isn't serving the application at ``https://www.example.com/`` and static files at ``https://static.example.com/`` a reasonable thing to do?

**Comment by evansd** [comment]
Well, it's certainly common to serve static files off a separate domain (which would usually be a CDN) but I've not generally seen them served at the root though. For instance, just looking at this GitHub page the files are served from `https://assets-cdn.github.com/assets/...`

**Comment by dominicrodger** [comment]
That sounds reasonable - might just be worth documenting the change, and making the error message clearer (I spent a while thinking I was going crazy - "but my settings *are* loaded").

I could have a go at this if you like :)

**Comment by evansd** [comment]
Sorry about that! The error message definitely needs improving, I'm going to push out a new release very shortly.

**Comment by dominicrodger** [comment]
Wonderful, thanks!

No apology needed - whitenoise has been hugely useful to me, so thanks for all your work on it!

**Comment by mpetyx** [comment]
I have the same issue with version 2.0.6. 
Is it somehow resolved?
I get the error,
` django.core.exceptions.ImproperlyConfigured: STATIC_URL setting must include a path component, for example: STATIC_URL = 'http://mydomain.cloudfront.net/static/'
`
I cannot find a workaround on this..

**Comment by evansd** [comment]
Have you tried setting `STATIC_URL` to the value suggested in the error message?

**Comment by mpetyx** [comment]
Yes.. 
In version 2.0.6, and by having my settings as
`STATIC_URL = "mydomain.cloudfront.net/static/"`
And then what i get is,
`http://127.0.0.1:8000/mydomain.cloudfront.net/img/mylogo.png`
instead of 
`mydomain.cloudfront.net/img/mylogo.png`
or 
`http://mydomain.cloudfront.net/img/mylogo.png`.
For me the response is not the desired because I want to avoid making requests to my server..

**Comment by evansd** [comment]
You've missed off the `http://` at the beginning of that string.

**Comment by mpetyx** [comment]
ooo yes yes my mistake. It also says that it needs a path component, whereas I do not have such because this specific cloudfront distribution is only set up to deliver static files.
Is there a way to have something like:
`STATIC_URL = "http://mydomain.cloudfront.net/"` ?

**Comment by evansd** [comment]
You do still need the path component because the static files are still served by your application which is where cloudfront fetches them from. Without the path component your static files would be mixed in with the other URLs served by your application.

**Comment by mpetyx** [comment]
ok... that means that I have to somehow move all of my files into a static folder within my S3 bucket, and then just add `STATIC_URL = "http://mydomain.cloudfront.net/static/"` to my settings.. Right?

**Comment by evansd** [comment]
Now I'm confused! How does the S3 bucket fit in here? WhiteNoise is supposed to be an alternative to pushing your static files to S3.

**Comment by mpetyx** [comment]
Now I start to understand...
I am already using django-storages and I had everything then on s3.
Now I needed to deploy on heroku, and thus I followed the tutorial for whitenoise which also worked.
But now that I needed to add cloudfront, I could not configure it, even though I created a cloudfront distribution based on the existing S3 bucket.
In the documentation [here](http://whitenoise.evans.io/en/latest/django.html#use-a-content-delivery-network-optional) it seems like there should be an existing cloudfront distribution (which most probably is an S3 bucket somewhere). So, somehow I have to move my static files to S3...
I just miss how whitenoise is going to work with CDN. How does it replicate my static files and then serve it (if it does not work with an S3 bucket)?
Thank you very very much for your help, I am just a bit confused with how whitenoise works..

**Comment by evansd** [comment]
When you set up the cloudfront distribution you give it the URL of your application and then it can fetch your static files from there.

There's a section in the docs that compares WhiteNoise and Django Storages which might be helpful to look at.

I think it's a much simpler setup overall, but it's quite a different approach so I can see that it might be confusing

Hope that helps.

**Comment by mpetyx** [comment]
Yes yes it is clear now. Thank you very much! 
I will try to understand whitenoise a little bit better.

**Comment by kentor** [comment]
What if I wanted `STATIC_URL` to be like `https://cdnurl.com/`, but when the cdn hits my django application, `https://cdnurl.com/<path>` is proxied to `https://origin/static/<path>`?

Is there a way to achieve that right now?

**Comment by evansd** [comment]
@kentor I think the only way to achieve that would be to subclass `DjangoWhiteNoise`. You could do something like this:
```python
class CustomWhiteNoise(DjangoWhiteNoise):

    def configure_from_settings(self, settings):
        super(CustomWhiteNoise, self).configure_from_settings(settings)
        self.static_prefix = getattr(settings, 'STATIC_PATH', '/static/')
```
I'm not sure what it would gain you though, compared to just requesting files from `https://cdnurl.com/static/<path>` in the first place.

**Comment by kentor** [comment]
@evansd thank you. that works. I wanted that to work for legacy reasons, to keep currently cached urls. Also, it gets confusing when whitenoise tries to configure itself from `STATIC_URL` because it seems like different libraries uses the same variable for their purposes, like django compressor for example.

**Comment by evansd** [comment]
@kentor In case you're interested, WhiteNoise now comes with a setting that will let you do what you want: http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_STATIC_PREFIX
