### ISSUE TITLE
ValueError files not found

### ISSUE THREAD

**Issue by richardcornish** [evansd/whitenoise#37]
I get a 500 (404?) error when trying to use whitenoise locally.

```
ValueError: The file 'css/bootstrap.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x10b13c050>.
```

Whenever `DEBUG` is `True`, everything works fine. When it's `False`, everything blows up. My static settings:

```
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static',),
)
STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
```

**Comment by evansd** [comment]
Have you run `python manage.py collectstatic` before running the server in non-debug mode?

**Comment by richardcornish** [comment]
Huh, that worked. But I also changed it to `STATIC_ROOT` to `STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')` and moved it to the bottom of settings.py. Thanks!
