### ISSUE TITLE
Compression not working

### ISSUE THREAD

**Issue by jakobholmelund** [evansd/whitenoise#38]
Hey guys. I hope you can help.

I have a setup running Django Pipeline with Django Whitenoise and everything seems to be working, but it doesn't. The gz files are generated perfectly, but it seems like whitenoise isn't serving the correct headers and thus, the browser doesn't fetch the gz files.

My setup is as follows
```
STATICFILES_STORAGE = 'sonofatailor.cached_storage.GzipManifestPipelineStorage'
```
where the storage class is defined as follows

```
from pipeline.storage import PipelineMixin
from whitenoise.django import GzipManifestStaticFilesStorage

class GzipManifestPipelineStorage(PipelineMixin, GzipManifestStaticFilesStorage):
    pass
```

This part seems to work great as stated above, and all the correct gz files are stored along side the other files

My wsgi.py looks lige this

```
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.prod")

from django.core.wsgi import get_wsgi_application
from whitenoise.django import DjangoWhiteNoise

application = get_wsgi_application()
application = DjangoWhiteNoise(application)
```

And i run my application through apache with

```
["python", "sonofatailorapp/manage_prod.py", "runmodwsgi", "config.wsgi", "--port=80", "--log-to-terminal", "--startup-log"]
```

where manage_prod.py looks like

```
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.prod")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

Can anybody spot, what i'm doing wrong ? 

The page is here http://107.178.250.104/ 

and you can test that the gz file is there and available here

http://107.178.250.104/static/scripts_dist/common.min.b947a82fca17.js
http://107.178.250.104/static/scripts_dist/common.min.b947a82fca17.js.gz

**Comment by evansd** [comment]
It looks like the files are being served by Apache, not by WhiteNoise. Here are the headers I get for `http://107.178.250.104/static/scripts_dist/common.min.b947a82fca17.js`:
```
Accept-Ranges: bytes
Content-Length: 311617
Content-Type :application/javascript
Date: Tue, 21 Jul 2015 14:52:59 GMT
ETag: "4c141-51b632630d500"
Last-Modified: Tue, 21 Jul 2015 14:05:40 GMT
Server: Apache/2.4.10 (Debian) mod_wsgi/4.4.12 Python/2.7.9
Via: 1.1 google
```

Possibly you have Apache configured to check for static files before proxying to Django.

**Comment by jakobholmelund** [comment]
That sounds very plausible. I haven't configured anything in Apache though. I'm simply using runmodwsgi(mod_wsgi-express). Any ideas to how i could stop apache messing with my staticfiles ? maybe moving them out of the project folder ?

**Comment by evansd** [comment]
It looks like `runmodwsgi` is to blame here, as it serves `STATIC_ROOT` if it's defined and there's no option to turn that behaviour off (I've just had a look at the code [here](https://github.com/GrahamDumpleton/mod_wsgi/blob/develop/src/server/management/commands/runmodwsgi.py).)

You could try filing a feature request with Graham to be able to disable that behaviour.

**Comment by jakobholmelund** [comment]
Dayum :/ Ill try and make a request with Graham. Or else i will just fire up the application with exec mod_wsgi-express instead. If whitenoise can handle the staticfiles, using runmodwsgi doesn't really add any convenience. I'll give it a go and report back

**Comment by jakobholmelund** [comment]
Seems to work when launching with mod_wsgi-express . My header now looks lige this 

```
Access-Control-Allow-Origin:*
Cache-Control:public, max-age=315360000
Connection:close
Content-Encoding:gzip
Content-Length:101250
Content-Type:application/javascript; charset="utf-8"
Date:Tue, 21 Jul 2015 17:55:49 GMT
Last-Modified:Tue, 21 Jul 2015 14:58:23 GMT
Server:Apache/2.4.10 (Debian) mod_wsgi/4.4.12 Python/2.7.9
Vary:Accept-Encoding
```
Is this correct ? I

**Comment by evansd** [comment]
Yep, that looks correct. Glad you got it working.
