### ISSUE TITLE
Gzip compression not being enabled

### ISSUE THREAD

**Issue by davegri** [evansd/whitenoise#39]
I'm a newbie so forgive me if I made a mistake but I've triple checked everything and I can't seem to figure out why Gzip compression is not being enabled.

**here is an example response header for a css file (from chrome dev-tools):**

    HTTP/1.1 304 Not Modified
    Content-Length: 0
    Connection: keep-alive
    Server: gunicorn/19.3.0
    Date: Tue, 18 Aug 2015 14:11:07 GMT
    Via: 1.1 vegur

package versions:
Django==1.8.3
gunicorn==19.3.0
whitenoise==2.0.2

**Static files configuration (settings.py)**

    BASE_DIR = os.path.dirname(os.path.dirname(__file__))
   
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static"),
    )

**wsgi.py**
    
    import os
    from django.core.wsgi import get_wsgi_application
    
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "sikumim.settings")
    
    application = get_wsgi_application()
    
    #HEROKU DEPLOYMENT
    
    from whitenoise.django import DjangoWhiteNoise
    application = DjangoWhiteNoise(application)
    
    # Fix django closing connection to MemCachier after every request (#11331)
    from django.core.cache.backends.memcached import BaseMemcachedCache
    BaseMemcachedCache.close = lambda self, **kwargs: None

**an example of how I'm loading static files in template:**
    
    {% load staticfiles %}
    <link href="{% static "css/base.css" %}" rel="stylesheet" type="text/css">

**extra production settings for Gzip:**

    STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

**Procfile:**

    web: gunicorn sikumim.wsgi

**Comment by evansd** [comment]
When you say "extra production settings for Gzip" does that mean that the `STATICFILES_STORAGE` setting isn't set by default but depends on some flag being enabled? If so, that's probably the source of the problem. `STATICFILES_STORAGE` needs to be set at the point when Heroku compiles your application slug, as that's when `collectstatic` gets run.

My advice would be to set `STATICFILES_STORAGE` as normal in `settings.py` for both production and development. There's no reason not to have it enabled in development.

**Comment by davegri** [comment]
Sorry, i'm an idiot.
thanks.
