### ISSUE TITLE
static file permission denied during collectstatic

### ISSUE THREAD

**Issue by pyth0nkod3r** [evansd/whitenoise#390]
### Python Version

3.10

### Django Version

4.0

### Package Version

6.1

### Description

I am using whitenoise to distribute static content. during an execution of runserver, in a development environment, I have the misfortune of experiencing a failed build. I get the below error whenever I run "python manage.py collectstatic"
Using the default Django storage engine gives no error. I'm using whitenoise v6.1.0.
I've given my static folder full permissions, yet the error persists

"""
You have requested to collect static files at the destination
location as specified in your settings: /storage/emulated/0/django/test_e/staticfiles This will overwrite existing files!
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: yes Traceback (most recent call last): File "/storage/emulated/0/django/test_e/manage.py", line 22, in main()
File "/storage/emulated/0/django/test_e/manage.py", line 18, in main execute_from_command_line(sys.argv)
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/init.py", line 446, in execute_from_command_line
utility.execute() File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/init.py", line 440, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
self.execute(*args, **cmd_options) File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
output = self.handle(*args, **options)
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
collected = self.collect()
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 148, in collect
for original_path, processed_path, processed in processor:
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/storage.py", line 162, in post_process_with_compression
for name, compressed_name in self.compress_files(files_to_compress):
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/storage.py", line 199, in compress_files
for compressed_path in compressor.compress(path):
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/compress.py", line 77, in compress
yield self.write_data(path, compressed, ".br", stat_result)
File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/compress.py", line 122, in write_data
os.utime(filename, (stat_result.st_atime, stat_result.st_mtime))
PermissionError: [Errno 1] Operation not permitted
"""

**Comment by adamchainz** [comment]
We can see the failure is due to the OS reporting no permission to changing the timestamps on the generated file.

You're going to need to provide more information - what filesystem are you using? what OS?

Perhaps we can ignore these exceptions for certain environments, but I'd like to know in what situations they can occur first.

**Comment by pyth0nkod3r** [comment]
I'm using termux on Android OS

**Comment by pyth0nkod3r** [comment]
Android 8.1 OS

**Comment by pyth0nkod3r** [comment]
Any updates on this issue?

**Comment by adamchainz** [comment]
@pyth0nkod3r I'm afraid you will need to take the initiative here. It looks like the `utime` system call is not working. This wouldn't normally fail when you have permissions to modify the file.

Can you check what filesystem is in use? You may also find a configuration option or permissions change to enable `utime` to work.

Ultimately we could wrap `try: / except PermissionError:` around the call to `utime()`, but I'd be hesitant to do that because it could silently hide real permissions misconfigurations (which may be what you're encountering).

**Comment by pyth0nkod3r** [comment]
@adamchainz
Filesystem in use is ext4 and I'm using a virtualenv.
Running "python manage.py collectstatic" works but eventually ends up with the permission error. However, my staticfiles get compiled and I'm able to successfully deploy without any errors.
I'm however concerned about what the error is and if anything might likely get broken later. Is there any likely workaround to resolve the error?

**Comment by pyth0nkod3r** [comment]
> It seems unusual to develop a django site on android! You may be the first person to hit this issue.
> 
> (not a whitenoise dev)

I don't have access to a pc and can't afford one right now. All  I've got is my android phone.

**Comment by pyth0nkod3r** [comment]
@adamchainz
I noticed that the error occurs when I add compression ie STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' results in an error but
STATICFILES_STORAGE = 'whitenoise.storage.ManifestStaticFilesStorage' without compression compiles successfully.

**Comment by pyth0nkod3r** [comment]
@adamchainz
I noticed that the error occurs when I add compression ie STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' results in an error but
STATICFILES_STORAGE = 'whitenoise.storage.ManifestStaticFilesStorage' without compression compiles successfully.

**Comment by adamchainz** [comment]
Closing this due to lack of information. I think we will just say that Whitenoise requires permissions to use `utime`.
