### ISSUE TITLE
Not serving compressed files

### ISSUE THREAD

**Issue by andyp05** [evansd/whitenoise#422]
### Python Version

3.10.7

### Django Version

4.1

### Package Version

6.2.0

### Description

Using Django on IIS and whitenoise is serving the css and js fine in uncompressed format. I have the settings for middleware 

`'whitenoise.middleware.WhiteNoiseMiddleware',`

and 

`STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' `

setup as documented. I have run collectstatic and the files are collected, the gz and br variants are created and the manifest json is created. 

When a static file is requested, whitenoise will return the plain/uncompressed js or css file. I can compress it using the cloudflare CDN, but I would like to understand why the brotli file is not sent from the origin. All built-in IIS compression is disabled. But if I enable it, I get the IIS compressed file (different file-size then the .br file on disk).

**Comment by adamchainz** [comment]
Is the `Accept-Encoding` header being sent correctly? How are you testing?

**Comment by andyp05** [comment]
Accept-Encoding is set to: `gzip, deflate, br`
Using Postman app to send request for a css file.
In this case, I now have it return gzip.

Edited Accept-Encoding to just `br`
IIS sends uncompressed file. Confirmed by looking at bytes downloaded.

The `test.css.br` file is in my static folder.

**Comment by adamchainz** [comment]
Browsers only use Brotli compression over HTTPS, it may be that IIS follows this. Are you testing over HTTPS?

**Comment by andyp05** [comment]
Yes it is over HTTPS. I tested and pulled a css file from another site and it came in as `br`
Whitenoise must be sending the file because I have Static File Handling in IIS turned off and the css file I get has the MD5 hash in the filename.

**Comment by adamchainz** [comment]
I'm afraid I can't help you further here, unless you can provide a simple reproduction (I've never used IIS, maybe you can give e.g. Docker commands to run it, along with a sample project).

But mostly I think you'll need to roll your sleeves up and debug each stage, maybe add print statements inside your app/whitenoise to see what headers are actually getting through, where Whitenoise is deciding not to send brotli, etc.

**Comment by andyp05** [comment]
Will do.
I will post any solution in case this comes up again for another user.
Thanks

**Comment by andyp05** [comment]
I am using Cloudflare CDN and they only request gzip from origin. I turned off proxy and put in development mode to test and the request is still gzip. That surprised me, but this issue is resolved. 
Thanks for your help.

**Comment by adamchainz** [comment]
Problem solved then!

**Comment by andyp05** [comment]
I am using Cloudflare CDN and they only request gzip from origin. I turned off proxy and put in development mode to test and the request is still gzip. That surprised me, but this issue is resolved. 
Thanks for your help.
