### ISSUE TITLE
Restrict *.map files

### ISSUE THREAD

**Issue by petrprikryl** [evansd/whitenoise#429]
### Description

Hi, I am curious about what you think of restricting access to `*.map ` files (js, css) served by whitenoise. 

Here is my working prototype for inspiration:

```
import re

from django.conf import settings
from django.core.exceptions import PermissionDenied

from ipware import get_client_ip
from whitenoise.middleware import WhiteNoiseMiddleware


class RestrictedWhiteNoiseMiddleware(WhiteNoiseMiddleware):
    re2ip = {re.compile(r"\.map$"): ["1.2.3.4", "5.6.7.8"]}

    def process_request(self, request):
        response = super().process_request(request)

        if response is not None and not self.is_path_allowed(request):
            raise PermissionDenied

        return response

    def is_path_allowed(self, request) -> bool:
        if settings.DEBUG:
            return True

        ip = get_client_ip(request)[0]
        for regex, ip_list in self.re2ip.items():
            if regex.search(request.path):
                return ip in ip_list

        return True

```

**Comment by adamchainz** [comment]
Trying to control access to source maps is pure *security theatre*. Attackers can run JavaScript through a de-minifier and figure out what it's doing. Even minified they can extrct the valuable strings, like endpoints.

That said, you're free to subclass whitenoise, as you've shown, to implement this charade, if your security team feels it is necessary.
