### ISSUE TITLE
Extend EXTRA_MIMETYPES from Django settings?

### ISSUE THREAD

**Issue by jcushman** [evansd/whitenoise#44]
It looks like the only way to extend EXTRA_MIMETYPES is by subclassing the `WhiteNoise` class. For Django projects, it might be nice to add mimetypes from `WHITENOISE_EXTRA_MIMETYPES` in `django.conf.settings` as well.

(FWIW, the mime type I'm missing is `('image/svg+xml', '.svg')`. Not sure how common that problem is.)

**Comment by evansd** [comment]
Yes, it would certainly be possible to do this. I had thought about adding this before but I didn't want to over-complicate the API until I knew whether it was a common requirement.

I was a bit surprised that you were missing the `.svg` mimetype as I thought that was defined by default. Looking into things more I see that the mimetypes module gets its data from a [list of system files](https://docs.python.org/2/library/mimetypes.html#mimetypes.knownfiles) which it checks for. This leaves the potential for things to work differently in development and production depending on the contents of these files. I'm now considering whether WhiteNoise ought to ship with its own set of default mimetypes to ensure consistency.

So, thanks for flagging this. I'll have to think about the best way forward but it is an issue that needs dealing with.

**Comment by jcushman** [comment]
Great, thanks for taking a look.

> This leaves the potential for things to work differently in development and production depending on the contents of these files.

Yeah, that was what bit me. I was working in a local Ubuntu environment and then deployed to a Red Hat server (asking for trouble, I know). After poking around a bit, it [appears](http://www.erikwebb.net/blog/compile-and-install-apache-24-red-hat-enterprise-linux-rhel-6-or-centos-6/) that Red Hat doesn't provide a mime.types file without installing the `mailcap` package:

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)
$ python
Python 2.7.10 (default, May 28 2015, 09:58:55)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mimetypes, os
>>> mimetypes.init()
>>> mimetypes.knownfiles
['/etc/mime.types', '/etc/httpd/mime.types', '/etc/httpd/conf/mime.types', '/etc/apache/mime.types', '/etc/apache2/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/lib/netscape/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/etc/mime.types']
>>> mimetypes.types_map['.svg']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '.svg' 
>>> for f in mimetypes.knownfiles: print f, len(open(f).read()) if os.path.exists(f) else "Not found."
...
/etc/mime.types Not found.
/etc/httpd/mime.types Not found.
/etc/httpd/conf/mime.types Not found.
/etc/apache/mime.types Not found.
/etc/apache2/mime.types Not found.
/usr/local/etc/httpd/conf/mime.types Not found.
/usr/local/lib/netscape/mime.types Not found.
/usr/local/etc/httpd/conf/mime.types Not found.
/usr/local/etc/mime.types Not found.
```

So, yeah -- on Red Hat, whitenoise basically has a hidden dependency on mailcap. Seems like good reason to ship with a list of mimetypes as you suggest. Thanks again for following up on this.
