### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by pamelafox** [evansd/whitenoise#457]
### Description

I noticed that the tox matrix for Github actions includes Python 3.11 (as of October 25th). Assuming the tests are passing, is it fair to say Python 3.11 is supported, or are you awaiting further evidence? 

The docs currently say that up to 3.10 is supported:
https://whitenoise.evans.io/en/stable/#compatibility

Thanks!

**Comment by adamchainz** [comment]
It's fully supported, just missed updating the docs. Fixed in 24cc31e.

**Comment by pamelafox** [comment]
Woot, thanks for updating the docs!
