### ISSUE TITLE
gzip.py module collides namespace with gzip module

### ISSUE THREAD

**Issue by piotr1212** [evansd/whitenoise#46]
gzip.py tries to import the gzip module but ends up importing itself. Apparently "." is added to the sys path by default. "." could be removed from the path but I think prettier way would be to rename gzip.py so that there is no name collision.

```
/usr/lib/python3.4/site-packages/whitenoise/gzip.py         
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/whitenoise/gzip.py", line 6, in <module>
    import gzip
  File "/usr/lib/python3.4/site-packages/whitenoise/gzip.py", line 15, in <module>
    GzipFile = gzip.GzipFile
AttributeError: 'module' object has no attribute 'GzipFile'
```

**Comment by evansd** [comment]
How are you invoking the script? This shouldn't happen if you use `python -m whitenoise.gzip` as recommended in the docs.

The file itself isn't executable, but I can see I've left a shebang line in there which is a mistake so I should take that out.

**Comment by piotr1212** [comment]
Yes, I noticed the shebang and assumed it was meant to call directly from commandline. It would be great If you could remove the shebang. thnx.
