### ISSUE TITLE
whitenoise is missing the argparse dependency when installed for Python 2.6

### ISSUE THREAD

**Issue by movermeyer** [evansd/whitenoise#47]
When you install whitenoise for Python 2.6:

    pip install whitenoise

It does not download the 'argparse' dependency automatically. Note that this library is included in the standard library for Python >= 2.7 and >= 3.2

If you try to use the whitenoise library without it (example from [Graphite](https://github.com/graphite-project/graphite-web)), you get:

    Traceback (most recent call last):
      File "/opt/graphite/conf/graphite.wsgi", line 32, in <module>
        from whitenoise.django import DjangoWhiteNoise
      File "/usr/lib/python2.6/site-packages/whitenoise/django.py", line 32, in <module>
        from .gzip import compress, extension_regex, GZIP_EXCLUDE_EXTENSIONS
      File "/usr/lib/python2.6/site-packages/whitenoise/gzip.py", line 4, in <module>
        import argparse
    ImportError: No module named argparse

**Comment by evansd** [comment]
@movermeyer A couple of questions on this:

1. What version of pip are you using? Using `extras_require` as discussed [here](https://github.com/evansd/whitenoise/pull/49) looks like the correct solution, but if you're stuck on Python 2.6 you may well be stuck on an older version of pip which doesn't support that.

2. Do you actually need to invoke the cli script (`python -m whitenoise.gzip`)? I could just restructure things so `argparse` isn't imported unless you're running the script in which case the issue probably wouldn't arise for the majority of 2.6 users.

**Comment by movermeyer** [comment]
1. I'm using the latest pip (7.1.2). [pip supports Python 2.6](https://pypi.python.org/pypi/pip/7.1.2).
I'm stuck on CentOS 6, which uses Python 2.6.6 by default :weary:

1. I'm actually not using whitenoise directly. The latest version of [Graphite](https://github.com/graphite-project/graphite-web) now uses whitenoise. You can see where they import it [here](https://github.com/graphite-project/graphite-web/blob/4028dc504c586fb8e38ad24b3ca35b1a66fe1619/conf/graphite.wsgi.example). Presumably, they are not doing something silly like shelling out to this script anywhere. Restructuring the code could hide the problem from the Python 2.6 users who don't use it as a script.
