### ISSUE TITLE
Azure app service web application is throwing 500 internal server error when using whitenoise - CompressedManifestStaticFilesStorage and DEBUG = False

### ISSUE THREAD

**Issue by karthimalyala** [evansd/whitenoise#481]
### Python Version

3.9

### Django Version

3.2

### Package Version
1.0

### Description

In my Django project settings.py file, i am using DEBUG = False and whitenoise to serve my static content on azure app services web application. 

When I use the following line which uses CompressedManifestStaticFilesStorage, I am getting 500 internal server error.

`STATICFILES_STORAGE = ('whitenoise.storage.CompressedManifestStaticFilesStorage')`

I was able to solve this problem by changing the above line to below,

`STATICFILES_STORAGE = ('whitenoise.storage.CompressedStaticFilesStorage')`

(or)

```
STORAGES={
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
```

I want to understand the rootcause of why it failed with DEBUG = False. We are not getting any error logs as well

With DEBUG = True, I don't see any error, it works fine but as you know it's not recommended to use Debug = True in production systems.

**Comment by adamchainz** [comment]
The error may be due to a reference to a static file that doesn't exist in the manifest.

If you aren't seeing an error message in your logs, try configure it so that they do show up. Maybe try Sentry.

**Comment by nerdbaggy** [comment]
I am having the same issue, I am still trying to debug it.

When I have the following
```
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
```

All of the template stuff using 'static' generates incorrect URL. With the above example my favicon static url is `/favicon.png` which causes the 500 error.  If I comment out that settings.py section above my favicon is correct at `/static/favicon.png`

**Comment by adamchainz** [comment]
I think this is behaviour from Django's `ManifestStaticFilesStorage`. As far as the manifest is concerned, the leading `/` makes it a different path that doesn't exist. We can't fix that here.
