### ISSUE TITLE
do not raise exception if sourceMappingURL rereferenced map is missing

### ISSUE THREAD

**Issue by mennucc** [evansd/whitenoise#499]
### Python Version

3.10

### Django Version

4.1

### Package Version

6.2.0

### Description

dear all,
in file _storage.py_ there are patterns to check if a static file requires other files.
One such pattern is
`//# sourceMappingURL=%(url)s`
if a _js_ file contains such statement,  but the referenced file is missing, then _whitenoise_ will raise exception on _collectstatic_ .
I think that this is overkill: source maps are used in debugging, but can be absent in all other cases. 
I propose that, if such statement is found, then _whitenoise_ may log a warning, but not raise an exception.
TIA.
a.

**Comment by adamchainz** [comment]
I am afraid this is behaviour inherited from Django, although I’m responsible for putting it there.

The rationale is that if you reference a file, you expect it to be there. Source maps are for debugging, but that may be debugging in your production environment. You probably want the source map to work if the comment is there.

If you want to change this behaviour, I would recommend starting a discussion on the Django forum. I know it has caused a couple of issues but overall I think there have not been many reports.
