### ISSUE TITLE
Should Whitenoise set CORS headers by default for all files?

### ISSUE THREAD

**Issue by evansd** [evansd/whitenoise#5]
Currently, Whitenoise sets an `Access-Control-Allow-Origin: *` header by default for all font files. This was done so that your fonts continue to work in Firefox if you're using a CDN.

I've since discovered other cases where CORS headers are needed, for instance the [respond.js](https://github.com/scottjehl/Respond) media query polyfill for IE which loads stylesheets over XHR.

I'm tempted to set  `Access-Control-Allow-Origin: *` header by default for **all** files. My reasoning is that:
1. it will mean that putting a CDN in front of Whitenoise _just works_, without any nasty cross-origin surprises;
2. given that Whitenoise only serves public, static files there are no security implications to allowing cross-origin requests.

I'm aware though that automatically setting these headers is a slightly surprising thing for an application to do and I'd really welcome feedback on whether people think it's a good idea.

**Comment by evilplanet** [comment]
> Currently, Whitenoise sets an Access-Control-Allow-Origin: * header by default for all font files. This was done so that your fonts continue to work in Firefox if you're using a CDN.

Does it? I'm using Whitenoise + Cloudfront, and my Font-Awesome files are not loading on Firefox. Any suggestions? @evansd

**Comment by evilplanet** [comment]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at .../static/fonts/fontawesome-webfont.b06871f281fe.ttf?v=4.7.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by evansd** [comment]
Maybe Cloudfront is filtering the header for some reason. Have you tried making a request directly against your site (i.e. not via Cloudfront) and checky whether the CORS header is set?

**Comment by evilplanet** [comment]
@evansd Do you mean before enabling Cloudfront? Yes the fonts loaded correctly with whitenoise before I enabled Cloudfront. 

I've added the following in my settings.py, will this help?
```
import mimetypes
# Additional MIME Types for web fonts
mimetypes.add_type("application/font-woff2", ".woff2", strict=True)
mimetypes.add_type("application/font-woff", ".woff", strict=True)
mimetypes.add_type("application/vnd.ms-fontobject", ".eot", strict=True)
mimetypes.add_type("application/x-font-opentype", ".otf", strict=True)
mimetypes.add_type("application/x-font-ttf", ".ttf", strict=True)
mimetypes.add_type("image/svg+xml", ".svg", strict=True)
# HTML5 video webm support
mimetypes.add_type("video/webm", ".webm", strict=True)
```

**Comment by evilplanet** [comment]
@evansd I think defining additional mimetypes as above did the trick. Now the fonts are loading correctly on Firefox.

**Comment by evilplanet** [comment]
I realised that whitenoise isn't just for django. So for anyone having the same issue, I'm using Django with Python3.

**Comment by caioariede** [comment]
> @evansd According to the W3C:
> A resource that is publicly accessible, with no access control checks, can always safely return an
> Access-Control-Allow-Origin header whose value is "*".
> ... which seems good enough for me.

Is this still true? I was looking at the most recent version of the document and it doesn't mention that anymore. I could only find that in the old document: https://www.w3.org/TR/2014/REC-cors-20140116/

**Comment by evansd** [comment]
@caioariede Ah, interesting that they've removed that line, but I imagine it just got lost in a reorganisation of the content rather than being deliberately removed. I'm pretty confident the logic is still sound though: public, static resources don't benefit from cross-origin restrictions.
