### ISSUE TITLE
Add ability to set a custom Content Type for specific files without an extension

### ISSUE THREAD

**Issue by iserko** [evansd/whitenoise#50]
Apple's `apple-app-site-association` file must be served with the `application/pkc7-mime` content type (see: https://developer.apple.com/library/ios/documentation/Security/Reference/SharedWebCredentialsRef/), but Whitenoise is serving it with `application/octet-stream`, because the file has no extension and as such `mimetypes` determines it should provide the default `octet-stream`.

Would it be feasible to have some sort of file -> content type mapping which we could use whenever you would like to override the `mimetypes` library.

**Comment by evansd** [comment]
I think the easiest way to handle this is to subclass WhiteNoise and use the `add_extra_headers` method which is explicitly provided to cope with these kinds of edge cases. The code would look something like this (untested):
```python
class CusomWhiteNoise(DjangoWhiteNoise):

    def add_extra_headers(self, headers, path, url):
        if url == '/apple-app-site-association':
            headers['Content-Type'] = 'application/pkcs7-mime'
```
Would that be an acceptable solution?

**Comment by iserko** [comment]
@evansd that solution works just fine thanks
