### ISSUE TITLE
SVGs showing up broken in the new Django 1.9 admin interface

### ISSUE THREAD

**Issue by aj-may** [evansd/whitenoise#52]
@evansd have you seen this happen before?

I haven't been able to dig into it very much yet.  If I gather any more info I'll update this issue.

**Comment by evansd** [comment]
Thanks for reporting this, I haven't seen this issue before.

Can you use the web inspector to grab the headers that are getting sent for these SVG files?

**Comment by evansd** [comment]
Any update on this? I'll assume this turned out not to be a WhiteNoise bug and close it if I don't hear anything.

**Comment by aj-may** [comment]
@evansd I set up a basic django 1.9 project to test it out and it worked fine.  Must be a misconfiguration in the other application.  Thanks.
