### ISSUE TITLE
Support redirecting to HTTPS / setting HSTS header

### ISSUE THREAD

**Issue by edmorley** [evansd/whitenoise#53]
Typically redirecting HTTP requests to HTTPS or setting an HSTS header would be the responsibility of ngnix/Apache, however when using Heroku these aren't an option.

One might say that the wgsi app that WhiteNoise wraps should handle this instead ([example](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-SECURE_SSL_REDIRECT)) -- since it could make the redirect when serving the homepage. 

However:
(a) this doesn't protect direct requests to static assets served by WhiteNoise (even if HSTS was enabled, the first visit to the site might be to a WhiteNoise served file instead)
(b) this doesn't help sites whose homepage is not dynamic, and is served by WhiteNoise itself (which is the case I hit, since the site UI is entirely Angular.js, with Django powering just the site API).

It's worth noting that when determining whether to redirect on Heroku, the `HTTP_X_FORWARDED_PROTO` header must be observed, since both HTTP and HTTPS requests arrive on the same port on the Heroku web dyno. (And similarly for Azure, one must check `x-arr-ssl`.)

I see three options:
1) Add support for redirects + HSTS in WhiteNoise.
2) Add an option for only serving requests over HTTPS via WhiteNoise, and let anything else fall through to the wrapped wgsi app so it can respond with the redirect/HSTS header itself.
3) Wontfix for WhiteNoise, but add recommendations to the docs for using some other wgsi wrapper that itself wraps WhiteNoise (though I'm struggling to find something generic).

@evansd, what are your thoughts? :-)

**Comment by evansd** [comment]
My first thought was that this would best be done by another, separate piece of WSGI middleware rather than bundling this functionality into WhiteNoise itself.

It turns out that Jacob Kaplan-Moss has already written exactly this: https://github.com/jacobian/wsgi-sslify

Seeing as he's a Django core commiter and Director of Security at Heroku, I'd feel happy recommending this in the docs.

**Comment by edmorley** [comment]
Ah that's perfect thank you - that package didn't show up in my searches, not sure why.
