### ISSUE TITLE
Are comments in CSS files respected?

### ISSUE THREAD

**Issue by txsl** [evansd/whitenoise#58]
I get an error that my CSS references a file which does not exist. I want to comment it out and deal with it at a later date, but both multiline and single line comments seem to be ignored and I still get the same error message.

For example,

`
/*url('../images/jumbotron-styled/bgbl.svg') bottom left no-repeat,*/
`

on its own line returns the error

> The CSS file 'css/usr/main.css' references a file which could not be found:
>   css/images/jumbotron-styled/bgbl.svg

> Please check the URL references in this CSS file, particularly any
> relative paths which might be pointing to the wrong location.

**Comment by evansd** [comment]
Unfortunately this is a known bug with Django's CachedStaticFilesStorage backend (it's not WhiteNoise-specific):
https://code.djangoproject.com/ticket/21080

I've been caught by the same thing before and ended up changing `url` to `urlNOT` as a quick and dirty way of avoiding the problem.
