### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) ;

### ISSUE THREAD

**Issue by nikoladang** [evansd/whitenoise#61]
I receive errors like this when access child page:
Failed to load resource: the server responded with a status of 404 (Not Found) ; http://www.dailyhn.com/news/2016/01/08/d3urtm1uacryxt.cloudfront.net/static/bootstrap-3.3.6/css/bootstrap.min.2f624089c65f.css

I don't know why...

**Comment by nikoladang** [comment]
When I'm on home page www.dailyhn.com, it's ok.
But when I click on an item on left-panel, it's crash.

**Comment by evansd** [comment]
Your STATIC_HOST setting is missing the leading forward slashes. It should be 
`//d3urtm1uacryxt.cloudfront.net``

Also, you have CloudFront misconfigured in some way: it's adding an extra `/static/` to the URL path.

**Comment by nikoladang** [comment]
This is my configuration:
# WhiteNoise
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
WHITENOISE_ROOT = os.path.join(BASE_DIR, "static")
STATIC_HOST = get_secret("DJANGO_STATIC_HOST")
STATIC_URL = STATIC_HOST + '/static/'


with {
...
"DJANGO_STATIC_HOST": "d3urtm1uacryxt.cloudfront.net"
...
}
