### ISSUE TITLE
{% static "/picture.jpg" %} does not work in production but works in development

### ISSUE THREAD

**Issue by johnmatthiggins** [evansd/whitenoise#621]
### Python Version

3.11.11

### Django Version

5.1.4

### Package Version

6.8.2

### Description

Whitenoise seems to treat leading slashes differently from Django's built in `django.contrib.staticfiles` debug mode.

If I do this in a django template:
`{% static "/picture.jpg" %}`
It works in debug mode, but when I run it in production with whitenoise configured, I get this error:
`ValueError: Missing staticfiles manifest entry for '/picture.jpg'`

I think whitenoise should ignore the slash at the beginning and treat it like "picture.jpg".

Here's a repository that replicates the problem.
https://github.com/johnmatthiggins/whitenoise-pathing-bug-reproduction

**Comment by evansd** [comment]
Hi @johnmatthiggins, this is behaviour from `contrib.staticfiles` and nothing specific to Whitenoise. If you change your storage engine to `django.contrib.staticfiles.storage.ManifestStaticFilesStorage` you'll see the same behaviour.
