### ISSUE TITLE
"No Module named Storage" 

### ISSUE THREAD

**Issue by kleeBoostable** [evansd/whitenoise#68]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

Gives a "No module named Storage error". The Django one does not.

In addition, if I use add this to MIDDLEWARE_CLASSES, 'whitenoise.middleware.WhiteNoiseMiddleware' I get a "no module named middleware" error

**Comment by evansd** [comment]
Please follow docs here http://whitenoise.evans.io for the currently released version of WhiteNoise. Docs on github relate to the development version
