### ISSUE TITLE
Not able to use WhiteNoiseMiddleware

### ISSUE THREAD

**Issue by jaxondu** [evansd/whitenoise#69]
I follow the 'QuickStart for Django apps' on the Github repo home page but got the error ImportError: No module named 'whitenoise.middleware'.

```
$ pip install whitenoise
Requirement already satisfied (use --upgrade to upgrade): whitenoise in /usr/local/lib/python3.5/site-packages

$ ls /usr/local/lib/python3.5/site-packages/whitenoise                             
__init__.py  __pycache__  base.py  django.py  gzip.py  management  storage_backport.py
```

It appears that middleware.py is not in the PIP install.

Also the "QuickStart for Django apps" on [whitenoise.evans.io/en/stable/](http://whitenoise.evans.io/en/stable/) is different from the Github repo.

**Comment by evansd** [comment]
Use the documentation on ReadTheDocs, github is where development happens and the docs there refer to the unreleased version.

**Comment by edmorley** [comment]
Perhaps the solution to this is to prune the readme so it only contains the description/first few paragraphs and then a link to read the docs stable branch for the rest? This would also avoid the current duplication between the readme and the docs index page, and make the quantity of information less overwhelming when visiting the repo on Github.

I'm happy to open a PR for this if you like the sound of that :-)

**Comment by evansd** [comment]
I was thinking about adding a warning to the readme, but your suggestion is much better. If you're happy to do a PR that would be great!
