### ISSUE TITLE
Remove now-redundant "Customising headers" section

### ISSUE THREAD

**Issue by edmorley** [evansd/whitenoise#74]
As of https://github.com/evansd/whitenoise/commit/48dd9392064bf2df0cb73569006da9bc29c055b5 / https://github.com/evansd/whitenoise/commit/c60809aa4c1498ecc4c86f6e843a3d4f07c7a23d , the docs added in #73 can probably be removed - since `add_headers_function` can be used instead of needing to subclass:
http://whitenoise.evans.io/en/latest/base.html#customising-headers

**Comment by evansd** [comment]
Fixed in 3c989a21f6a4c1e62bc3a8218d793976f785196c
