### ISSUE TITLE
Figure out how to make `runserver_nostatic` work with Channels

### ISSUE THREAD

**Issue by evansd** [evansd/whitenoise#77]
At present, `runserver_nostatic` works by simply shadowing the `runserver` command from `contrib.staticfiles` and replacing it with the `runserver` command from Django core. However, this won't work with Channels, which needs its own [runserver command](https://github.com/andrewgodwin/channels/blob/master/channels/management/commands/runserver.py).

A possible approach might be to require that `runserver_nostatic` be at the top of the `INSTALLED_APPS` list and for it to discover the next highest priority `runserver` command (by inspecting the [app registry](https://docs.djangoproject.com/en/1.9/ref/applications/#application-registry) and delegate to that, after setting the appropriate `--no-static` flag.

This is obviously more complex and fragile, but it would be nice to have a simple (for the user) solution which was agnostic as to whether Channels was being used.

**Comment by amureki** [comment]
@evansd 

maybe not very related, but I wonder if whitenoise is working with current channels approach?
for example,
```
from channels.asgi import get_channel_layer
from whitenoise import WhiteNoise

channel_layer = get_channel_layer()
channel_layer = WhiteNoise(channel_layer)
```
would not work, of course, but is there any way to make it work?

**Comment by evansd** [comment]
@amureki 

Yes, you can now integrate WhiteNoise by adding it to `settings.MIDDLEWARE_CLASSES` rather than editing `wsgi.py`. This works with standard Django and with Channels.

See:
http://whitenoise.evans.io/en/stable/changelog.html#simpler-cleaner-django-middleware-integration

**Comment by edevil** [comment]
So can this be closed?

**Comment by evansd** [comment]
@edevil No, I don't think so. WhiteNoise works fine with Channels, but the small "runserver_nostatic" feature doesn't. You can either ignore the issue in which case your app will use the default static file handling when in DEBUG mode, or you can manually pass the `--nostatic` option to runserver.

**Comment by sajoku** [comment]
I also ran into this and had `channels` defined after `'whitenoise.runserver_nostatic',`. This will run the server `runserver` fine but does not initiate the channels part. Very confusing (also because I'm new to Django and Python probably). So it seems there's nothing wrong with the configuration but the channels part will not be loaded at all. Even doing 
```
CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "asgiref.inmemory.ChannelLayer",
            "ROUTING": "uadoua.routing.channel_routing",
            },
        }
```
Where `uadoua.routing.channel_routing` is non existent will not fail and just run the server.

I'm running versions:

```
whitenoise==3.3.0
Django==1.11.1
```

From above discussion I would think this will fail in the proposed solution right?

**Comment by lwm** [comment]
FYI, Got bitten by this one pretty badly folks over at https://github.com/django/channels/issues/684. We probably should come up with a fix here. At the very least, a runtime warning.

**Comment by edmorley** [comment]
I wonder if a better solution is to upstream a fix to Django that adds a way to disable the `contrib.staticfiles` via configuration pref or similar?

**Comment by evansd** [comment]
Fixed in ce74438, which will form part of the upcoming 4.0 release.

**Comment by typistX** [comment]
@evansd Can I use 4.0 right now? My site is **extremely** slow with Channels 2 & WhiteNoise

**Comment by timkofu** [comment]
Is this still an issue with `Django 4x`, `Channels 3x` and `Whitenoise 6x`?

**Comment by adamchainz** [comment]
There was a commit to fix this. Did you try? Please also don't comment on 5 year old issues, only open a new one if you have information.
