### ISSUE TITLE
More about the purpose

### ISSUE THREAD

**Issue by techtonik** [evansd/whitenoise#79]
I can't see exact problematic for WhiteNoise - it surely exists, just not exposed in documentation as something that is easily catched when scanning the text.

I remeber I had really hard times debugging server configuration when application had settings to serve static files and then somebody overrided it with server config. And also development setup was different from production and I could not catch the bugs. Does whitenoise prevent that by using single point of configuration for both development and production static service? If yes, it maybe worth to dedicate a chapter to this user story.

**Comment by evansd** [comment]
I try to explain what the point of WhiteNoise is here:
http://whitenoise.evans.io/en/stable/index.html

Does that help at all?

**Comment by techtonik** [comment]
Well, no.

> With a couple of lines of config WhiteNoise allows your web app to serve its own static files

Well, many (most?) frameworks come with support for serving static files already - https://docs.djangoproject.com/en/1.9/howto/static-files/

**Comment by evansd** [comment]
Quoting from the page you linked to:

> This method is grossly inefficient and probably insecure, so it is unsuitable for production.

**Comment by techtonik** [comment]
But it seems like whitenoise doesn't serve it too.
