### ISSUE TITLE
Question: does local development mode of whitenoise append hash to the file name?

### ISSUE THREAD

**Issue by khanhlu2013** [evansd/whitenoise#81]

**Comment by evansd** [comment]
Not by default, no. All the hashing is done by Django's [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#manifeststaticfilesstorage) class and that doesn't generated hashed filenames when `DEBUG=True`. WhiteNoise will still serve any hashed files if they're requested, it's just that the storage backend won't generated the right URLs in development.
