### ISSUE TITLE
Handling HTTP Range headers (partial content) for video streaming

### ISSUE THREAD

**Issue by bu2** [evansd/whitenoise#82]
Hi David, 

I am using Whitenoise and it works great !

The only thing is my Django app needs to stream a MP4 video to iOS devices (running a Safari web app). And it seems that modern Safari (iOS 9.x and OS X) refuses to read MP4 videos when the server does not support Range requests ([Hypertext Transfer Protocol (HTTP/1.1): Range Requests](https://tools.ietf.org/html/rfc7233)).

Basically, the web browser requests the MP4 video with an additional header (ex: RANGE: bytes=0-1023) and the server should respond with the first 1024 bytes of the full response (in my case a video static file).

Do you see any roadblock if I try to implement support for Range requests in Whitenoise.server() ?

Note: usually we do not need to handle those kind of requests in pure Python/Django because  Apache/NginX support those headers.

Regards.

**Comment by evansd** [comment]
Interesting. I didn't know that Apple had this requirement but the [docs](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6) say that you're correct.

I assume you're going to be behind some kind of CDN in production, not serving video directly to users via Python?

Annoyingly it seems that, although CloudFront will serve `Range` requests correctly to clients even if the origin server doesn't support them, it will only do so once the object's in the cache (see [here](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RangeGETs.html)). So the first request for the video won't play, but then subsequent requests will.

In any case, it would be better not to rely the specifics of CloudFront's behaviour here. I'd be open to supporting this if it can be done without harming performance for normal non-Range requests.

**Comment by bu2** [comment]
Hi David,

I just got a first naive implementation that works. So I am going to do some clean up and submit a pull request.

For the details: I am working on an embedded systems which will stream medias and should operate online and offline... so there is a lot of specific constraints (this is not a typical web environment). And the fact that the whole app is relying on Python only is a very good thing.

Regards.

**Comment by evansd** [comment]
Hi, just to say thanks for the PR. I haven't forgotten about this issue but I've been busy with other stuff. I can't merge your PR as it stands but it's a useful starting point and I think I've got a plan for how to implement this. Hopefully I'll get a chance to do it before too long!

**Comment by gregplaysguitar** [comment]
Can I suggest that this limitation be added to the docs in the mean time?

**Comment by hz-stevec** [comment]
Any movement on this? Asking because it makes debugging video locally really difficult, and going through the build process to push to test/staging is time intensive.

Thanks!

**Comment by evansd** [comment]
This has finally been added in the upcoming 4.0 release.

**Comment by racitup** [comment]
In case it helps someone:
https://github.com/racitup/static-ranges
