### ISSUE TITLE
Possible Bug: Nested Assets 

### ISSUE THREAD

**Issue by joshblum** [evansd/whitenoise#84]
I'm using whitenoise to cache assets within an angular app. There currently seems to be a bug if there are nested assets. For example, if i have `index.js` which references a partial `index.html`, if `index.js` is processed first, `index.html -> index.<hash-key>.html`. Then if `index.html` is processed and rehashed (i.e. this file contains references to `index.png`), the `<hash-key>` inside of `index.js` in incorrect, since `index.html` was rehashed to account for it's own static assets. Are there currently any work arounds (besides naming your dependencies in alphabetical order) to avoid this issue?

**Comment by edmorley** [comment]
WhiteNoise's storage backend is only a very think wrapper around Django's ManifestStaticFilesStorage backend:
https://github.com/evansd/whitenoise/blob/master/whitenoise/storage.py

Does this issue occur if you use the stock Django backend directly? See:
http://whitenoise.evans.io/en/stable/django.html#storage-troubleshoot

**Comment by joshblum** [comment]
Yeah digging into the django source, it seems they have a bug in how they process :)

**Comment by edmorley** [comment]
Thank you for updating this issue - if you end up filing a Django ticket perhaps post the link here in case others hit the same problem.

Have a great day!

**Comment by joshblum** [comment]
Will do, thanks!

**Comment by joshblum** [comment]
For reference: https://code.djangoproject.com/ticket/26527#ticket
