### ISSUE TITLE
Static files not served in StaticLiveServerTestCase?

### ISSUE THREAD

**Issue by JonHannah** [evansd/whitenoise#86]
I'm developing a Django application with Heroku deployment. I am trying to round out test coverage with some django.test.Client get requests within a StaticLiveServerTestCase. These run fine locally, and files are served fine on the actual site, but my test fails on CircleCI / Heroku:

  ```... ...
File "/home/ubuntu/virtualenvs/venv-3.5.0/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'search/css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x7f65c2a60be0>.```

Not a serious blocker, but would welcome any suggestions!

**Comment by edmorley** [comment]
Does the issue still exist when using the native Django storage backend (WhiteNoise's backend is only a thin wrapper around it)?
http://whitenoise.evans.io/en/stable/django.html#troubleshooting-the-whitenoise-storage-backend

**Comment by JonHannah** [comment]
Thanks for the prompt response. I tried this, but in doing so realised my problem wasn't really with Whitenoise or Heroku, but actually with getting my tests to run on CircleCI. I added the below to my circle.yml file and all is well.

```
test:
  pre:
    - "python manage.py collectstatic --no-input"```

**Comment by edmorley** [comment]
Ah yes that would do it :-)

I almost asked whether collectstatic had been run, but I read the issue description as meaning Heroku was affected too, and collectstatic is run there automatically (courtesy of [this script](https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/collectstatic)).

Thank you for updating the ticket!

**Comment by martyzz1** [comment]
It could be worth updateding the docs... I just ran into this issue on circleci too...

**Comment by JonHannah** [comment]
Which docs? It actually feels like something which belongs on CircleCI docs: "Don't forget to add collecstatic if you run Django client tests"

**Comment by lisad** [comment]
I've run into this problem too now, and it seems like a non-optimal workaround.  Why is it working any differently on CircleCI than on my development environment? Shouldn't tests run in an environment where whitenoise pulls the static files out of their source directories not their collected destination?

**Comment by evansd** [comment]
@lisad  Your tests must be running with `DEBUG = False`, whereas you development environment is running with  `DEBUG = True`.

It's up to you how you want to run your tests, however most people do so with debug-mode disabled so as to better replicate the production environment.

**Comment by lisad** [comment]
Fair point @evansd.  I suppose putting 'collectstatic' in there before the test run serves to test that the static files will be there in production as expected.
