### ISSUE TITLE
Fallback if manifest fails

### ISSUE THREAD

**Issue by joshblum** [evansd/whitenoise#87]
Would it be possible to fallback to serving the original file if it is not found in the manifest? It would be nice if there was a graceful way to fail if the manifest is corrupted (i.e. at least the file is served, even if it is inefficient)

**Comment by evansd** [comment]
This behaviour is a feature of Django's [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#manifeststaticfilesstorage) backend, not something specific to WhiteNoise, so you'd need to raise this request with Django itself.

**Comment by joshblum** [comment]
Gotcha thanks!
