### ISSUE TITLE
Check Python version rather than just importability of `http.client`

### ISSUE THREAD

**Issue by evansd** [evansd/whitenoise#93]
Someone has published a package called [http](https://pypi.python.org/pypi/http) so it's possible that `http.client` imports successfully on Python 2.7, but doesn't provide the correct interface.

We should explicitly check the Python version before attempting the import. This should prevent issues like #92 from occurring again.

**Comment by evansd** [comment]
Or possibly, stop trying to be clever and just define the constants we need in `httpstatus_backport` rather than trying to dredge them out of the stdlib somehow.

**Comment by edmorley** [comment]
WhiteNoise currently only uses `METHOD_NOT_ALLOWED`, `OK` and `NOT_MODIFIED` from `HTTPStatus` - so maybe just defining them as constants for Python 2.7-3.4 makes sense? (It's not like the list can get out of sync - they're not being used with user-provided input).

**Comment by evansd** [comment]
@edmorley Yep, it's the totally obvious solution in retrospect. I'm not sure why I went down that dynamic meta-programming rabbit hole :)

**Comment by edmorley** [comment]
:-)
