### ISSUE TITLE
Support for static files changing after application start

### ISSUE THREAD

**Issue by rfleschenberg** [evansd/whitenoise#95]
Hi,

On some setups (e.g. django-compressor without offline compression), some static files are only written to the storage when they are requested for the first time. As far as I see, whitenoise does not support such a scenario at the moment, because it scans the filesystem at application start.

django-compressor has a [signal](https://django-compressor.readthedocs.io/en/latest/usage/#signals) that could be used to notify whitenoise when a static file has changed.

Is there a good solution for this? If not, would you be open to adding support for this scenario?

**Comment by edmorley** [comment]
Even if support was added to WhiteNoise for listening to these signals, writing files after the application starts seems suboptimal for several reasons:
1) In the case of eg Heroku, the slug has already been built - so any computation has to be repeated for every web dyno & won't be persisted after dyno restart (which happens every 24 hours) or after deploy.
2) For the first time each file is requested on each dyno (and taking into account [1]), the request will take much longer.
3) Presuming the WhiteNoise support was roughly: "if the file doesn't exist, fallback to the Django wsgi app, then catch the signal and add to the WhiteNoise files list for the next request", this still means Django would have to serve the file for that first request, which doesn't work when not using runserver. This would also likely mean inconsistent behaviour between first and second requests for a file (eg headers; hence why we have [the overriding runserver feature](http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development) as-is).

Is there a use-case I'm missing as to why django-compressor's offline mode can't just be used? (Seeing as for development, whitenoise already supports auto-refresh)

**Comment by rfleschenberg** [comment]
I understand this would not be a very good spot to be in for Heroku users (I am actually using whitenoise with gunicorn + nginx on my own boxes).

As for possible support in whitenoise, I was thinking about something more simple: just provide some kind of "rescan files" hook. I could then write a Django signal handler that listens for the `post_compress` signal and calls that hook. Performance-wise, this should not make a difference for people who do not use it. For those who use it, the first request to a not-yet-generated file will be slow (but maybe not that much slower than when using on-demand generation and serving it from nginx), but once the file is generated, performance should again be identical to offline compression. But I have to admit that I did not think this through very carefully. Are there any problems with this approach that I failed to consider?

I totally agree that offline compression is preferable and would turn this into a non-issue. I might be able to fix my application to work with offline compression in the future, and I plan to look into this. For the time being, I had to remove whitenoise from my setup, which is a little annoying because I now have to deal with the "few lines of nginx config" problems mentioned in the [IAQ](http://whitenoise.evans.io/en/stable/index.html#what-s-the-point-in-whitenoise-when-i-can-do-the-same-thing-in-a-few-lines-of-apache-nginx-config).

**Comment by evansd** [comment]
Yes, I agree with everything @edmorley said.

The signals based approach won't work if you're running multiple application processes (as almost everyone does) because signals aren't cross-process. So one process will generate the static file and fire a signal to get its own instance of WhiteNoise to rescan, but none of the other process will know to rescan their files.

Whether you're running on Heroku or not you'll be much better off generating your static files in advance.
