### ISSUE TITLE
'CompressedManifestStaticFilesStorage' object has no attribute '_normalize_name'

### ISSUE THREAD

**Issue by exp0nge** [evansd/whitenoise#97]
I get `'CompressedManifestStaticFilesStorage' object has no attribute '_normalize_name'` when I have `collectfast` as one of my apps.

**Comment by evansd** [comment]
`collectfast` is only designed to work with files stored on Amazon S3, so you can't use it with WhiteNoise which stores its files locally. Even if you could get it to work it wouldn't give you any performance benefit when using local files.
