### ISSUE TITLE
Use stream compression.

### ISSUE THREAD

**Issue by pahaz** [evansd/whitenoise#98]
It\`s bad idea use `data = file.read()` for compression.

If file have large size?

**Comment by evansd** [comment]
Yes, it used to use stream-based compression when it was gzip only, but the [brotlipy](http://python-hyper.org/projects/brotlipy/en/latest/) package which I'm using for brotli compression [doesn't support](https://github.com/python-hyper/brotlipy/blob/21c66d7d5c88e0ed495bbc8a0b74b844ff4a17d4/src/brotli/brotli.py#L24) that.

The compressor skips over image, video and flash files and so should only be running on smaller text-based files. If your CSS or JavaScript is too big to load into memory then you have other problems!

**Comment by edmorley** [comment]
If you can think of any omissions from the file extension skip-list ([see here](https://github.com/evansd/whitenoise/blob/v3.2/whitenoise/compress.py#L21-L29)), do let us know :-)

Or for cases specific to your situation, the list can be overridden using eg:
http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_SKIP_COMPRESS_EXTENSIONS
